package com.naver.mage4j.core.mage.core.model.resource.session;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CoreSession generated by hbm2java
 */
@Entity
@Table(name = "core_session"
	, catalog = "magento")
public class CoreSession implements java.io.Serializable {
	public static final long SEESION_MAX_COOKIE_LIFETIME = 3155692600L;

	private String sessionId;
	private int sessionExpires;
	private byte[] sessionData;

	private transient final SessionHelper helper;

	public CoreSession() {
		super();

		helper = new SessionHelper(this);
	}

	public CoreSession(String sessionId, int sessionExpires, byte[] sessionData) {
		this();
		this.sessionId = sessionId;
		this.sessionExpires = sessionExpires;
		this.sessionData = sessionData;
	}

	@Transient
	public SessionHelper getHelper() {
		return helper;
	}

	@Id
	@Column(name = "session_id", unique = true, nullable = false)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "session_expires", nullable = false)
	public int getSessionExpires() {
		return this.sessionExpires;
	}

	public void setSessionExpires(int sessionExpires) {
		this.sessionExpires = sessionExpires;
	}

	@Column(name = "session_data", nullable = false, columnDefinition="mediumblob")
	public byte[] getSessionData() {
		return this.sessionData;
	}

	public void setSessionData(byte[] sessionData) {
		this.sessionData = sessionData;
	}

}
