package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Api2AclAttribute generated by hbm2java
 */
@Entity
@Table(name = "api2_acl_attribute"
	, catalog = "magento"
	, uniqueConstraints = @UniqueConstraint(columnNames = {"user_type", "resource_id", "operation"}))
public class Api2AclAttribute implements java.io.Serializable {

	private Integer entityId;
	private String userType;
	private String resourceId;
	private String operation;
	private String allowedAttributes;

	public Api2AclAttribute() {
	}

	public Api2AclAttribute(String userType, String resourceId, String operation) {
		this.userType = userType;
		this.resourceId = resourceId;
		this.operation = operation;
	}

	public Api2AclAttribute(String userType, String resourceId, String operation, String allowedAttributes) {
		this.userType = userType;
		this.resourceId = resourceId;
		this.operation = operation;
		this.allowedAttributes = allowedAttributes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@Column(name = "user_type", nullable = false, length = 20)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "resource_id", nullable = false)
	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "operation", nullable = false, length = 20)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "allowed_attributes", length = 65535)
	public String getAllowedAttributes() {
		return this.allowedAttributes;
	}

	public void setAllowedAttributes(String allowedAttributes) {
		this.allowedAttributes = allowedAttributes;
	}

}
