package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Api2AclRule generated by hbm2java
 */
@Entity
@Table(name = "api2_acl_rule"
	, catalog = "magento"
	, uniqueConstraints = @UniqueConstraint(columnNames = {"role_id", "resource_id", "privilege"}))
public class Api2AclRule implements java.io.Serializable {

	private Integer entityId;
	private Api2AclRole api2AclRole;
	private String resourceId;
	private String privilege;

	public Api2AclRule() {
	}

	public Api2AclRule(Api2AclRole api2AclRole, String resourceId) {
		this.api2AclRole = api2AclRole;
		this.resourceId = resourceId;
	}

	public Api2AclRule(Api2AclRole api2AclRole, String resourceId, String privilege) {
		this.api2AclRole = api2AclRole;
		this.resourceId = resourceId;
		this.privilege = privilege;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Api2AclRole getApi2AclRole() {
		return this.api2AclRole;
	}

	public void setApi2AclRole(Api2AclRole api2AclRole) {
		this.api2AclRole = api2AclRole;
	}

	@Column(name = "resource_id", nullable = false)
	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "privilege", length = 20)
	public String getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(String privilege) {
		this.privilege = privilege;
	}

}
