package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApiUser generated by hbm2java
 */
@Entity
@Table(name = "api_user"
	, catalog = "magento")
public class ApiUser implements java.io.Serializable {

	private Integer userId;
	private String firstname;
	private String lastname;
	private String email;
	private String username;
	private String apiKey;
	private Date created;
	private Date modified;
	private short lognum;
	private short reloadAclFlag;
	private short isActive;
	private Set<ApiSession> apiSessions = new HashSet<ApiSession>(0);

	public ApiUser() {
	}

	public ApiUser(Date created, short lognum, short reloadAclFlag, short isActive) {
		this.created = created;
		this.lognum = lognum;
		this.reloadAclFlag = reloadAclFlag;
		this.isActive = isActive;
	}

	public ApiUser(String firstname, String lastname, String email, String username, String apiKey, Date created, Date modified, short lognum, short reloadAclFlag, short isActive, Set<ApiSession> apiSessions) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.username = username;
		this.apiKey = apiKey;
		this.created = created;
		this.modified = modified;
		this.lognum = lognum;
		this.reloadAclFlag = reloadAclFlag;
		this.isActive = isActive;
		this.apiSessions = apiSessions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "firstname", length = 32)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 32)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", length = 40)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "api_key", length = 100)
	public String getApiKey() {
		return this.apiKey;
	}

	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "lognum", nullable = false)
	public short getLognum() {
		return this.lognum;
	}

	public void setLognum(short lognum) {
		this.lognum = lognum;
	}

	@Column(name = "reload_acl_flag", nullable = false)
	public short getReloadAclFlag() {
		return this.reloadAclFlag;
	}

	public void setReloadAclFlag(short reloadAclFlag) {
		this.reloadAclFlag = reloadAclFlag;
	}

	@Column(name = "is_active", nullable = false)
	public short getIsActive() {
		return this.isActive;
	}

	public void setIsActive(short isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apiUser")
	public Set<ApiSession> getApiSessions() {
		return this.apiSessions;
	}

	public void setApiSessions(Set<ApiSession> apiSessions) {
		this.apiSessions = apiSessions;
	}

}
