package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatalogProductIndexPriceBundleSelTmp generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_index_price_bundle_sel_tmp"
	, catalog = "magento")
public class CatalogProductIndexPriceBundleSelTmp implements java.io.Serializable {

	private CatalogProductIndexPriceBundleSelTmpId id;
	private Short groupType;
	private Short isRequired;
	private BigDecimal price;
	private BigDecimal tierPrice;
	private BigDecimal groupPrice;

	public CatalogProductIndexPriceBundleSelTmp() {
	}

	public CatalogProductIndexPriceBundleSelTmp(CatalogProductIndexPriceBundleSelTmpId id) {
		this.id = id;
	}

	public CatalogProductIndexPriceBundleSelTmp(CatalogProductIndexPriceBundleSelTmpId id, Short groupType, Short isRequired, BigDecimal price, BigDecimal tierPrice, BigDecimal groupPrice) {
		this.id = id;
		this.groupType = groupType;
		this.isRequired = isRequired;
		this.price = price;
		this.tierPrice = tierPrice;
		this.groupPrice = groupPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "entityId", column = @Column(name = "entity_id", nullable = false)),
		@AttributeOverride(name = "customerGroupId", column = @Column(name = "customer_group_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false)),
		@AttributeOverride(name = "optionId", column = @Column(name = "option_id", nullable = false)),
		@AttributeOverride(name = "selectionId", column = @Column(name = "selection_id", nullable = false))})
	public CatalogProductIndexPriceBundleSelTmpId getId() {
		return this.id;
	}

	public void setId(CatalogProductIndexPriceBundleSelTmpId id) {
		this.id = id;
	}

	@Column(name = "group_type")
	public Short getGroupType() {
		return this.groupType;
	}

	public void setGroupType(Short groupType) {
		this.groupType = groupType;
	}

	@Column(name = "is_required")
	public Short getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(Short isRequired) {
		this.isRequired = isRequired;
	}

	@Column(name = "price", precision = 12, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "tier_price", precision = 12, scale = 4)
	public BigDecimal getTierPrice() {
		return this.tierPrice;
	}

	public void setTierPrice(BigDecimal tierPrice) {
		this.tierPrice = tierPrice;
	}

	@Column(name = "group_price", precision = 12, scale = 4)
	public BigDecimal getGroupPrice() {
		return this.groupPrice;
	}

	public void setGroupPrice(BigDecimal groupPrice) {
		this.groupPrice = groupPrice;
	}

}
