package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatalogProductEntityMediaGalleryValueId generated by hbm2java
 */
@Embeddable
public class CatalogProductEntityMediaGalleryValueId implements java.io.Serializable {

	private int valueId;
	private short storeId;

	public CatalogProductEntityMediaGalleryValueId() {
	}

	public CatalogProductEntityMediaGalleryValueId(int valueId, short storeId) {
		this.valueId = valueId;
		this.storeId = storeId;
	}

	@Column(name = "value_id", nullable = false)
	public int getValueId() {
		return this.valueId;
	}

	public void setValueId(int valueId) {
		this.valueId = valueId;
	}

	@Column(name = "store_id", nullable = false)
	public short getStoreId() {
		return this.storeId;
	}

	public void setStoreId(short storeId) {
		this.storeId = storeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatalogProductEntityMediaGalleryValueId))
			return false;
		CatalogProductEntityMediaGalleryValueId castOther = (CatalogProductEntityMediaGalleryValueId)other;

		return (this.getValueId() == castOther.getValueId())
			&& (this.getStoreId() == castOther.getStoreId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getValueId();
		result = 37 * result + this.getStoreId();
		return result;
	}

}
