package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatalogProductIndexPriceBundleTmp generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_index_price_bundle_tmp"
	, catalog = "magento")
public class CatalogProductIndexPriceBundleTmp implements java.io.Serializable {

	private CatalogProductIndexPriceBundleTmpId id;
	private Short taxClassId;
	private short priceType;
	private BigDecimal specialPrice;
	private BigDecimal tierPercent;
	private BigDecimal origPrice;
	private BigDecimal price;
	private BigDecimal minPrice;
	private BigDecimal maxPrice;
	private BigDecimal tierPrice;
	private BigDecimal baseTier;
	private BigDecimal groupPrice;
	private BigDecimal baseGroupPrice;
	private BigDecimal groupPricePercent;

	public CatalogProductIndexPriceBundleTmp() {
	}

	public CatalogProductIndexPriceBundleTmp(CatalogProductIndexPriceBundleTmpId id, short priceType) {
		this.id = id;
		this.priceType = priceType;
	}

	public CatalogProductIndexPriceBundleTmp(CatalogProductIndexPriceBundleTmpId id, Short taxClassId, short priceType, BigDecimal specialPrice, BigDecimal tierPercent, BigDecimal origPrice, BigDecimal price, BigDecimal minPrice, BigDecimal maxPrice, BigDecimal tierPrice, BigDecimal baseTier, BigDecimal groupPrice, BigDecimal baseGroupPrice, BigDecimal groupPricePercent) {
		this.id = id;
		this.taxClassId = taxClassId;
		this.priceType = priceType;
		this.specialPrice = specialPrice;
		this.tierPercent = tierPercent;
		this.origPrice = origPrice;
		this.price = price;
		this.minPrice = minPrice;
		this.maxPrice = maxPrice;
		this.tierPrice = tierPrice;
		this.baseTier = baseTier;
		this.groupPrice = groupPrice;
		this.baseGroupPrice = baseGroupPrice;
		this.groupPricePercent = groupPricePercent;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "entityId", column = @Column(name = "entity_id", nullable = false)),
		@AttributeOverride(name = "customerGroupId", column = @Column(name = "customer_group_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false))})
	public CatalogProductIndexPriceBundleTmpId getId() {
		return this.id;
	}

	public void setId(CatalogProductIndexPriceBundleTmpId id) {
		this.id = id;
	}

	@Column(name = "tax_class_id")
	public Short getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(Short taxClassId) {
		this.taxClassId = taxClassId;
	}

	@Column(name = "price_type", nullable = false)
	public short getPriceType() {
		return this.priceType;
	}

	public void setPriceType(short priceType) {
		this.priceType = priceType;
	}

	@Column(name = "special_price", precision = 12, scale = 4)
	public BigDecimal getSpecialPrice() {
		return this.specialPrice;
	}

	public void setSpecialPrice(BigDecimal specialPrice) {
		this.specialPrice = specialPrice;
	}

	@Column(name = "tier_percent", precision = 12, scale = 4)
	public BigDecimal getTierPercent() {
		return this.tierPercent;
	}

	public void setTierPercent(BigDecimal tierPercent) {
		this.tierPercent = tierPercent;
	}

	@Column(name = "orig_price", precision = 12, scale = 4)
	public BigDecimal getOrigPrice() {
		return this.origPrice;
	}

	public void setOrigPrice(BigDecimal origPrice) {
		this.origPrice = origPrice;
	}

	@Column(name = "price", precision = 12, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "min_price", precision = 12, scale = 4)
	public BigDecimal getMinPrice() {
		return this.minPrice;
	}

	public void setMinPrice(BigDecimal minPrice) {
		this.minPrice = minPrice;
	}

	@Column(name = "max_price", precision = 12, scale = 4)
	public BigDecimal getMaxPrice() {
		return this.maxPrice;
	}

	public void setMaxPrice(BigDecimal maxPrice) {
		this.maxPrice = maxPrice;
	}

	@Column(name = "tier_price", precision = 12, scale = 4)
	public BigDecimal getTierPrice() {
		return this.tierPrice;
	}

	public void setTierPrice(BigDecimal tierPrice) {
		this.tierPrice = tierPrice;
	}

	@Column(name = "base_tier", precision = 12, scale = 4)
	public BigDecimal getBaseTier() {
		return this.baseTier;
	}

	public void setBaseTier(BigDecimal baseTier) {
		this.baseTier = baseTier;
	}

	@Column(name = "group_price", precision = 12, scale = 4)
	public BigDecimal getGroupPrice() {
		return this.groupPrice;
	}

	public void setGroupPrice(BigDecimal groupPrice) {
		this.groupPrice = groupPrice;
	}

	@Column(name = "base_group_price", precision = 12, scale = 4)
	public BigDecimal getBaseGroupPrice() {
		return this.baseGroupPrice;
	}

	public void setBaseGroupPrice(BigDecimal baseGroupPrice) {
		this.baseGroupPrice = baseGroupPrice;
	}

	@Column(name = "group_price_percent", precision = 12, scale = 4)
	public BigDecimal getGroupPricePercent() {
		return this.groupPricePercent;
	}

	public void setGroupPricePercent(BigDecimal groupPricePercent) {
		this.groupPricePercent = groupPricePercent;
	}

}
