package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CatalogProductIndexGroupPrice generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_index_group_price"
	, catalog = "magento")
public class CatalogProductIndexGroupPrice implements java.io.Serializable {

	private CatalogProductIndexGroupPriceId id;
	private CoreWebsite coreWebsite;
	private CatalogProductEntity catalogProductEntity;
	private CustomerGroup customerGroup;
	private BigDecimal price;

	public CatalogProductIndexGroupPrice() {
	}

	public CatalogProductIndexGroupPrice(CatalogProductIndexGroupPriceId id, CoreWebsite coreWebsite, CatalogProductEntity catalogProductEntity, CustomerGroup customerGroup) {
		this.id = id;
		this.coreWebsite = coreWebsite;
		this.catalogProductEntity = catalogProductEntity;
		this.customerGroup = customerGroup;
	}

	public CatalogProductIndexGroupPrice(CatalogProductIndexGroupPriceId id, CoreWebsite coreWebsite, CatalogProductEntity catalogProductEntity, CustomerGroup customerGroup, BigDecimal price) {
		this.id = id;
		this.coreWebsite = coreWebsite;
		this.catalogProductEntity = catalogProductEntity;
		this.customerGroup = customerGroup;
		this.price = price;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "entityId", column = @Column(name = "entity_id", nullable = false)),
		@AttributeOverride(name = "customerGroupId", column = @Column(name = "customer_group_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false))})
	public CatalogProductIndexGroupPriceId getId() {
		return this.id;
	}

	public void setId(CatalogProductIndexGroupPriceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "website_id", nullable = false, insertable = false, updatable = false)
	public CoreWebsite getCoreWebsite() {
		return this.coreWebsite;
	}

	public void setCoreWebsite(CoreWebsite coreWebsite) {
		this.coreWebsite = coreWebsite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entity_id", nullable = false, insertable = false, updatable = false)
	public CatalogProductEntity getCatalogProductEntity() {
		return this.catalogProductEntity;
	}

	public void setCatalogProductEntity(CatalogProductEntity catalogProductEntity) {
		this.catalogProductEntity = catalogProductEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_group_id", nullable = false, insertable = false, updatable = false)
	public CustomerGroup getCustomerGroup() {
		return this.customerGroup;
	}

	public void setCustomerGroup(CustomerGroup customerGroup) {
		this.customerGroup = customerGroup;
	}

	@Column(name = "price", precision = 12, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
