package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatalogProductIndexPriceFinalTmp generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_index_price_final_tmp"
	, catalog = "magento")
public class CatalogProductIndexPriceFinalTmp implements java.io.Serializable {

	private CatalogProductIndexPriceFinalTmpId id;
	private Short taxClassId;
	private BigDecimal origPrice;
	private BigDecimal price;
	private BigDecimal minPrice;
	private BigDecimal maxPrice;
	private BigDecimal tierPrice;
	private BigDecimal baseTier;
	private BigDecimal groupPrice;
	private BigDecimal baseGroupPrice;

	public CatalogProductIndexPriceFinalTmp() {
	}

	public CatalogProductIndexPriceFinalTmp(CatalogProductIndexPriceFinalTmpId id) {
		this.id = id;
	}

	public CatalogProductIndexPriceFinalTmp(CatalogProductIndexPriceFinalTmpId id, Short taxClassId, BigDecimal origPrice, BigDecimal price, BigDecimal minPrice, BigDecimal maxPrice, BigDecimal tierPrice, BigDecimal baseTier, BigDecimal groupPrice, BigDecimal baseGroupPrice) {
		this.id = id;
		this.taxClassId = taxClassId;
		this.origPrice = origPrice;
		this.price = price;
		this.minPrice = minPrice;
		this.maxPrice = maxPrice;
		this.tierPrice = tierPrice;
		this.baseTier = baseTier;
		this.groupPrice = groupPrice;
		this.baseGroupPrice = baseGroupPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "entityId", column = @Column(name = "entity_id", nullable = false)),
		@AttributeOverride(name = "customerGroupId", column = @Column(name = "customer_group_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false))})
	public CatalogProductIndexPriceFinalTmpId getId() {
		return this.id;
	}

	public void setId(CatalogProductIndexPriceFinalTmpId id) {
		this.id = id;
	}

	@Column(name = "tax_class_id")
	public Short getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(Short taxClassId) {
		this.taxClassId = taxClassId;
	}

	@Column(name = "orig_price", precision = 12, scale = 4)
	public BigDecimal getOrigPrice() {
		return this.origPrice;
	}

	public void setOrigPrice(BigDecimal origPrice) {
		this.origPrice = origPrice;
	}

	@Column(name = "price", precision = 12, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "min_price", precision = 12, scale = 4)
	public BigDecimal getMinPrice() {
		return this.minPrice;
	}

	public void setMinPrice(BigDecimal minPrice) {
		this.minPrice = minPrice;
	}

	@Column(name = "max_price", precision = 12, scale = 4)
	public BigDecimal getMaxPrice() {
		return this.maxPrice;
	}

	public void setMaxPrice(BigDecimal maxPrice) {
		this.maxPrice = maxPrice;
	}

	@Column(name = "tier_price", precision = 12, scale = 4)
	public BigDecimal getTierPrice() {
		return this.tierPrice;
	}

	public void setTierPrice(BigDecimal tierPrice) {
		this.tierPrice = tierPrice;
	}

	@Column(name = "base_tier", precision = 12, scale = 4)
	public BigDecimal getBaseTier() {
		return this.baseTier;
	}

	public void setBaseTier(BigDecimal baseTier) {
		this.baseTier = baseTier;
	}

	@Column(name = "group_price", precision = 12, scale = 4)
	public BigDecimal getGroupPrice() {
		return this.groupPrice;
	}

	public void setGroupPrice(BigDecimal groupPrice) {
		this.groupPrice = groupPrice;
	}

	@Column(name = "base_group_price", precision = 12, scale = 4)
	public BigDecimal getBaseGroupPrice() {
		return this.baseGroupPrice;
	}

	public void setBaseGroupPrice(BigDecimal baseGroupPrice) {
		this.baseGroupPrice = baseGroupPrice;
	}

}
