package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CataloginventoryStockStatusTmp generated by hbm2java
 */
@Entity
@Table(name = "cataloginventory_stock_status_tmp"
	, catalog = "magento")
public class CataloginventoryStockStatusTmp implements java.io.Serializable {

	private CataloginventoryStockStatusTmpId id;
	private BigDecimal qty;
	private short stockStatus;

	public CataloginventoryStockStatusTmp() {
	}

	public CataloginventoryStockStatusTmp(CataloginventoryStockStatusTmpId id, BigDecimal qty, short stockStatus) {
		this.id = id;
		this.qty = qty;
		this.stockStatus = stockStatus;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false)),
		@AttributeOverride(name = "stockId", column = @Column(name = "stock_id", nullable = false))})
	public CataloginventoryStockStatusTmpId getId() {
		return this.id;
	}

	public void setId(CataloginventoryStockStatusTmpId id) {
		this.id = id;
	}

	@Column(name = "qty", nullable = false, precision = 12, scale = 4)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "stock_status", nullable = false)
	public short getStockStatus() {
		return this.stockStatus;
	}

	public void setStockStatus(short stockStatus) {
		this.stockStatus = stockStatus;
	}

}
