package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatalogCategoryAncCategsIndexTmp generated by hbm2java
 */
@Entity
@Table(name = "catalog_category_anc_categs_index_tmp"
	, catalog = "magento")
public class CatalogCategoryAncCategsIndexTmp implements java.io.Serializable {

	private CatalogCategoryAncCategsIndexTmpId id;

	public CatalogCategoryAncCategsIndexTmp() {
	}

	public CatalogCategoryAncCategsIndexTmp(CatalogCategoryAncCategsIndexTmpId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)),
		@AttributeOverride(name = "path", column = @Column(name = "path"))})
	public CatalogCategoryAncCategsIndexTmpId getId() {
		return this.id;
	}

	public void setId(CatalogCategoryAncCategsIndexTmpId id) {
		this.id = id;
	}

}
