package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatalogProductBundleStockIndex generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_bundle_stock_index"
	, catalog = "magento")
public class CatalogProductBundleStockIndex implements java.io.Serializable {

	private CatalogProductBundleStockIndexId id;
	private Short stockStatus;

	public CatalogProductBundleStockIndex() {
	}

	public CatalogProductBundleStockIndex(CatalogProductBundleStockIndexId id) {
		this.id = id;
	}

	public CatalogProductBundleStockIndex(CatalogProductBundleStockIndexId id, Short stockStatus) {
		this.id = id;
		this.stockStatus = stockStatus;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "entityId", column = @Column(name = "entity_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false)),
		@AttributeOverride(name = "stockId", column = @Column(name = "stock_id", nullable = false)),
		@AttributeOverride(name = "optionId", column = @Column(name = "option_id", nullable = false))})
	public CatalogProductBundleStockIndexId getId() {
		return this.id;
	}

	public void setId(CatalogProductBundleStockIndexId id) {
		this.id = id;
	}

	@Column(name = "stock_status")
	public Short getStockStatus() {
		return this.stockStatus;
	}

	public void setStockStatus(Short stockStatus) {
		this.stockStatus = stockStatus;
	}

}
