package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CataloginventoryStockStatusId generated by hbm2java
 */
@Embeddable
public class CataloginventoryStockStatusId implements java.io.Serializable {

	private int productId;
	private short websiteId;
	private short stockId;

	public CataloginventoryStockStatusId() {
	}

	public CataloginventoryStockStatusId(int productId, short websiteId, short stockId) {
		this.productId = productId;
		this.websiteId = websiteId;
		this.stockId = stockId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "website_id", nullable = false)
	public short getWebsiteId() {
		return this.websiteId;
	}

	public void setWebsiteId(short websiteId) {
		this.websiteId = websiteId;
	}

	@Column(name = "stock_id", nullable = false)
	public short getStockId() {
		return this.stockId;
	}

	public void setStockId(short stockId) {
		this.stockId = stockId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CataloginventoryStockStatusId))
			return false;
		CataloginventoryStockStatusId castOther = (CataloginventoryStockStatusId)other;

		return (this.getProductId() == castOther.getProductId())
			&& (this.getWebsiteId() == castOther.getWebsiteId())
			&& (this.getStockId() == castOther.getStockId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getWebsiteId();
		result = 37 * result + this.getStockId();
		return result;
	}

}
