package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatalogCategoryProductIndexEnblIdx generated by hbm2java
 */
@Entity
@Table(name = "catalog_category_product_index_enbl_idx"
	, catalog = "magento")
public class CatalogCategoryProductIndexEnblIdx implements java.io.Serializable {

	private CatalogCategoryProductIndexEnblIdxId id;

	public CatalogCategoryProductIndexEnblIdx() {
	}

	public CatalogCategoryProductIndexEnblIdx(CatalogCategoryProductIndexEnblIdxId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
		@AttributeOverride(name = "visibility", column = @Column(name = "visibility", nullable = false))})
	public CatalogCategoryProductIndexEnblIdxId getId() {
		return this.id;
	}

	public void setId(CatalogCategoryProductIndexEnblIdxId id) {
		this.id = id;
	}

}
