package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CronSchedule generated by hbm2java
 */
@Entity
@Table(name = "cron_schedule"
	, catalog = "magento")
public class CronSchedule implements java.io.Serializable {

	private Integer scheduleId;
	private String jobCode;
	private String status;
	private String messages;
	private Date createdAt;
	private Date scheduledAt;
	private Date executedAt;
	private Date finishedAt;

	public CronSchedule() {
	}

	public CronSchedule(String jobCode, String status, Date createdAt) {
		this.jobCode = jobCode;
		this.status = status;
		this.createdAt = createdAt;
	}

	public CronSchedule(String jobCode, String status, String messages, Date createdAt, Date scheduledAt, Date executedAt, Date finishedAt) {
		this.jobCode = jobCode;
		this.status = status;
		this.messages = messages;
		this.createdAt = createdAt;
		this.scheduledAt = scheduledAt;
		this.executedAt = executedAt;
		this.finishedAt = finishedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "schedule_id", unique = true, nullable = false)
	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	@Column(name = "job_code", nullable = false)
	public String getJobCode() {
		return this.jobCode;
	}

	public void setJobCode(String jobCode) {
		this.jobCode = jobCode;
	}

	@Column(name = "status", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "messages", length = 65535)
	public String getMessages() {
		return this.messages;
	}

	public void setMessages(String messages) {
		this.messages = messages;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduled_at", length = 19)
	public Date getScheduledAt() {
		return this.scheduledAt;
	}

	public void setScheduledAt(Date scheduledAt) {
		this.scheduledAt = scheduledAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "executed_at", length = 19)
	public Date getExecutedAt() {
		return this.executedAt;
	}

	public void setExecutedAt(Date executedAt) {
		this.executedAt = executedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "finished_at", length = 19)
	public Date getFinishedAt() {
		return this.finishedAt;
	}

	public void setFinishedAt(Date finishedAt) {
		this.finishedAt = finishedAt;
	}

}
