package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerGroup generated by hbm2java
 */
@Entity
@Table(name = "customer_group"
	, catalog = "magento")
public class CustomerGroup implements java.io.Serializable {

	private Short customerGroupId;
	private String customerGroupCode;
	private int taxClassId;
	private Set<CatalogruleGroupWebsite> catalogruleGroupWebsites = new HashSet<CatalogruleGroupWebsite>(0);
	private Set<Catalogrule> catalogrules = new HashSet<Catalogrule>(0);
	private Set<CatalogProductIndexGroupPrice> catalogProductIndexGroupPrices = new HashSet<CatalogProductIndexGroupPrice>(0);
	private Set<CatalogProductBundlePriceIndex> catalogProductBundlePriceIndexes = new HashSet<CatalogProductBundlePriceIndex>(0);
	private Set<CatalogruleProduct> catalogruleProducts = new HashSet<CatalogruleProduct>(0);
	private Set<WeeeDiscount> weeeDiscounts = new HashSet<WeeeDiscount>(0);
	private Set<CatalogruleProductPrice> catalogruleProductPrices = new HashSet<CatalogruleProductPrice>(0);
	private Set<CatalogProductIndexPrice> catalogProductIndexPrices = new HashSet<CatalogProductIndexPrice>(0);
	private Set<CatalogProductEntityGroupPrice> catalogProductEntityGroupPrices = new HashSet<CatalogProductEntityGroupPrice>(0);
	private Set<CatalogProductIndexTierPrice> catalogProductIndexTierPrices = new HashSet<CatalogProductIndexTierPrice>(0);
	private Set<Salesrule> salesrules = new HashSet<Salesrule>(0);
	private Set<SalesruleProductAttribute> salesruleProductAttributes = new HashSet<SalesruleProductAttribute>(0);
	private Set<CatalogProductEntityTierPrice> catalogProductEntityTierPrices = new HashSet<CatalogProductEntityTierPrice>(0);

	public CustomerGroup() {
	}

	public CustomerGroup(String customerGroupCode, int taxClassId) {
		this.customerGroupCode = customerGroupCode;
		this.taxClassId = taxClassId;
	}

	public CustomerGroup(String customerGroupCode, int taxClassId, Set<CatalogruleGroupWebsite> catalogruleGroupWebsites, Set<Catalogrule> catalogrules, Set<CatalogProductIndexGroupPrice> catalogProductIndexGroupPrices, Set<CatalogProductBundlePriceIndex> catalogProductBundlePriceIndexes, Set<CatalogruleProduct> catalogruleProducts, Set<WeeeDiscount> weeeDiscounts, Set<CatalogruleProductPrice> catalogruleProductPrices, Set<CatalogProductIndexPrice> catalogProductIndexPrices,
		Set<CatalogProductEntityGroupPrice> catalogProductEntityGroupPrices, Set<CatalogProductIndexTierPrice> catalogProductIndexTierPrices, Set<Salesrule> salesrules, Set<SalesruleProductAttribute> salesruleProductAttributes, Set<CatalogProductEntityTierPrice> catalogProductEntityTierPrices) {
		this.customerGroupCode = customerGroupCode;
		this.taxClassId = taxClassId;
		this.catalogruleGroupWebsites = catalogruleGroupWebsites;
		this.catalogrules = catalogrules;
		this.catalogProductIndexGroupPrices = catalogProductIndexGroupPrices;
		this.catalogProductBundlePriceIndexes = catalogProductBundlePriceIndexes;
		this.catalogruleProducts = catalogruleProducts;
		this.weeeDiscounts = weeeDiscounts;
		this.catalogruleProductPrices = catalogruleProductPrices;
		this.catalogProductIndexPrices = catalogProductIndexPrices;
		this.catalogProductEntityGroupPrices = catalogProductEntityGroupPrices;
		this.catalogProductIndexTierPrices = catalogProductIndexTierPrices;
		this.salesrules = salesrules;
		this.salesruleProductAttributes = salesruleProductAttributes;
		this.catalogProductEntityTierPrices = catalogProductEntityTierPrices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_group_id", unique = true, nullable = false)
	public Short getCustomerGroupId() {
		return this.customerGroupId;
	}

	public void setCustomerGroupId(Short customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

	@Column(name = "customer_group_code", nullable = false, length = 32)
	public String getCustomerGroupCode() {
		return this.customerGroupCode;
	}

	public void setCustomerGroupCode(String customerGroupCode) {
		this.customerGroupCode = customerGroupCode;
	}

	@Column(name = "tax_class_id", nullable = false)
	public int getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(int taxClassId) {
		this.taxClassId = taxClassId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogruleGroupWebsite> getCatalogruleGroupWebsites() {
		return this.catalogruleGroupWebsites;
	}

	public void setCatalogruleGroupWebsites(Set<CatalogruleGroupWebsite> catalogruleGroupWebsites) {
		this.catalogruleGroupWebsites = catalogruleGroupWebsites;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "customerGroups")
	public Set<Catalogrule> getCatalogrules() {
		return this.catalogrules;
	}

	public void setCatalogrules(Set<Catalogrule> catalogrules) {
		this.catalogrules = catalogrules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogProductIndexGroupPrice> getCatalogProductIndexGroupPrices() {
		return this.catalogProductIndexGroupPrices;
	}

	public void setCatalogProductIndexGroupPrices(Set<CatalogProductIndexGroupPrice> catalogProductIndexGroupPrices) {
		this.catalogProductIndexGroupPrices = catalogProductIndexGroupPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogProductBundlePriceIndex> getCatalogProductBundlePriceIndexes() {
		return this.catalogProductBundlePriceIndexes;
	}

	public void setCatalogProductBundlePriceIndexes(Set<CatalogProductBundlePriceIndex> catalogProductBundlePriceIndexes) {
		this.catalogProductBundlePriceIndexes = catalogProductBundlePriceIndexes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogruleProduct> getCatalogruleProducts() {
		return this.catalogruleProducts;
	}

	public void setCatalogruleProducts(Set<CatalogruleProduct> catalogruleProducts) {
		this.catalogruleProducts = catalogruleProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<WeeeDiscount> getWeeeDiscounts() {
		return this.weeeDiscounts;
	}

	public void setWeeeDiscounts(Set<WeeeDiscount> weeeDiscounts) {
		this.weeeDiscounts = weeeDiscounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogruleProductPrice> getCatalogruleProductPrices() {
		return this.catalogruleProductPrices;
	}

	public void setCatalogruleProductPrices(Set<CatalogruleProductPrice> catalogruleProductPrices) {
		this.catalogruleProductPrices = catalogruleProductPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogProductIndexPrice> getCatalogProductIndexPrices() {
		return this.catalogProductIndexPrices;
	}

	public void setCatalogProductIndexPrices(Set<CatalogProductIndexPrice> catalogProductIndexPrices) {
		this.catalogProductIndexPrices = catalogProductIndexPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogProductEntityGroupPrice> getCatalogProductEntityGroupPrices() {
		return this.catalogProductEntityGroupPrices;
	}

	public void setCatalogProductEntityGroupPrices(Set<CatalogProductEntityGroupPrice> catalogProductEntityGroupPrices) {
		this.catalogProductEntityGroupPrices = catalogProductEntityGroupPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogProductIndexTierPrice> getCatalogProductIndexTierPrices() {
		return this.catalogProductIndexTierPrices;
	}

	public void setCatalogProductIndexTierPrices(Set<CatalogProductIndexTierPrice> catalogProductIndexTierPrices) {
		this.catalogProductIndexTierPrices = catalogProductIndexTierPrices;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "customerGroups")
	public Set<Salesrule> getSalesrules() {
		return this.salesrules;
	}

	public void setSalesrules(Set<Salesrule> salesrules) {
		this.salesrules = salesrules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<SalesruleProductAttribute> getSalesruleProductAttributes() {
		return this.salesruleProductAttributes;
	}

	public void setSalesruleProductAttributes(Set<SalesruleProductAttribute> salesruleProductAttributes) {
		this.salesruleProductAttributes = salesruleProductAttributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CatalogProductEntityTierPrice> getCatalogProductEntityTierPrices() {
		return this.catalogProductEntityTierPrices;
	}

	public void setCatalogProductEntityTierPrices(Set<CatalogProductEntityTierPrice> catalogProductEntityTierPrices) {
		this.catalogProductEntityTierPrices = catalogProductEntityTierPrices;
	}

}
