package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CustomerEavAttribute generated by hbm2java
 */
@Entity
@Table(name = "customer_eav_attribute"
	, catalog = "magento")
public class CustomerEavAttribute implements java.io.Serializable {

	private short attributeId;
	private EavAttribute eavAttribute;
	private short isVisible;
	private String inputFilter;
	private short multilineCount;
	private String validateRules;
	private short isSystem;
	private int sortOrder;
	private String dataModel;

	public CustomerEavAttribute() {
	}

	public CustomerEavAttribute(EavAttribute eavAttribute, short isVisible, short multilineCount, short isSystem, int sortOrder) {
		this.eavAttribute = eavAttribute;
		this.isVisible = isVisible;
		this.multilineCount = multilineCount;
		this.isSystem = isSystem;
		this.sortOrder = sortOrder;
	}

	public CustomerEavAttribute(EavAttribute eavAttribute, short isVisible, String inputFilter, short multilineCount, String validateRules, short isSystem, int sortOrder, String dataModel) {
		this.eavAttribute = eavAttribute;
		this.isVisible = isVisible;
		this.inputFilter = inputFilter;
		this.multilineCount = multilineCount;
		this.validateRules = validateRules;
		this.isSystem = isSystem;
		this.sortOrder = sortOrder;
		this.dataModel = dataModel;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "eavAttribute"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "attribute_id", unique = true, nullable = false)
	public short getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(short attributeId) {
		this.attributeId = attributeId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public EavAttribute getEavAttribute() {
		return this.eavAttribute;
	}

	public void setEavAttribute(EavAttribute eavAttribute) {
		this.eavAttribute = eavAttribute;
	}

	@Column(name = "is_visible", nullable = false)
	public short getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(short isVisible) {
		this.isVisible = isVisible;
	}

	@Column(name = "input_filter")
	public String getInputFilter() {
		return this.inputFilter;
	}

	public void setInputFilter(String inputFilter) {
		this.inputFilter = inputFilter;
	}

	@Column(name = "multiline_count", nullable = false)
	public short getMultilineCount() {
		return this.multilineCount;
	}

	public void setMultilineCount(short multilineCount) {
		this.multilineCount = multilineCount;
	}

	@Column(name = "validate_rules", length = 65535)
	public String getValidateRules() {
		return this.validateRules;
	}

	public void setValidateRules(String validateRules) {
		this.validateRules = validateRules;
	}

	@Column(name = "is_system", nullable = false)
	public short getIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(short isSystem) {
		this.isSystem = isSystem;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "data_model")
	public String getDataModel() {
		return this.dataModel;
	}

	public void setDataModel(String dataModel) {
		this.dataModel = dataModel;
	}

}
