package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerEavAttributeWebsiteId generated by hbm2java
 */
@Embeddable
public class CustomerEavAttributeWebsiteId implements java.io.Serializable {

	private short attributeId;
	private short websiteId;

	public CustomerEavAttributeWebsiteId() {
	}

	public CustomerEavAttributeWebsiteId(short attributeId, short websiteId) {
		this.attributeId = attributeId;
		this.websiteId = websiteId;
	}

	@Column(name = "attribute_id", nullable = false)
	public short getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(short attributeId) {
		this.attributeId = attributeId;
	}

	@Column(name = "website_id", nullable = false)
	public short getWebsiteId() {
		return this.websiteId;
	}

	public void setWebsiteId(short websiteId) {
		this.websiteId = websiteId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomerEavAttributeWebsiteId))
			return false;
		CustomerEavAttributeWebsiteId castOther = (CustomerEavAttributeWebsiteId)other;

		return (this.getAttributeId() == castOther.getAttributeId())
			&& (this.getWebsiteId() == castOther.getWebsiteId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAttributeId();
		result = 37 * result + this.getWebsiteId();
		return result;
	}

}
