package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DirectoryCurrencyRateId generated by hbm2java
 */
@Embeddable
public class DirectoryCurrencyRateId implements java.io.Serializable {

	private String currencyFrom;
	private String currencyTo;

	public DirectoryCurrencyRateId() {
	}

	public DirectoryCurrencyRateId(String currencyFrom, String currencyTo) {
		this.currencyFrom = currencyFrom;
		this.currencyTo = currencyTo;
	}

	@Column(name = "currency_from", nullable = false, length = 3)
	public String getCurrencyFrom() {
		return this.currencyFrom;
	}

	public void setCurrencyFrom(String currencyFrom) {
		this.currencyFrom = currencyFrom;
	}

	@Column(name = "currency_to", nullable = false, length = 3)
	public String getCurrencyTo() {
		return this.currencyTo;
	}

	public void setCurrencyTo(String currencyTo) {
		this.currencyTo = currencyTo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DirectoryCurrencyRateId))
			return false;
		DirectoryCurrencyRateId castOther = (DirectoryCurrencyRateId)other;

		return ((this.getCurrencyFrom() == castOther.getCurrencyFrom()) || (this.getCurrencyFrom() != null && castOther.getCurrencyFrom() != null && this.getCurrencyFrom().equals(castOther.getCurrencyFrom())))
			&& ((this.getCurrencyTo() == castOther.getCurrencyTo()) || (this.getCurrencyTo() != null && castOther.getCurrencyTo() != null && this.getCurrencyTo().equals(castOther.getCurrencyTo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCurrencyFrom() == null ? 0 : this.getCurrencyFrom().hashCode());
		result = 37 * result + (getCurrencyTo() == null ? 0 : this.getCurrencyTo().hashCode());
		return result;
	}

}
