package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DirectoryCountry generated by hbm2java
 */
@Entity
@Table(name = "directory_country"
	, catalog = "magento")
public class DirectoryCountry implements java.io.Serializable {

	private String countryId;
	private String iso2Code;
	private String iso3Code;
	private Set<WeeeTax> weeeTaxes = new HashSet<WeeeTax>(0);

	public DirectoryCountry() {
	}

	public DirectoryCountry(String countryId) {
		this.countryId = countryId;
	}

	public DirectoryCountry(String countryId, String iso2Code, String iso3Code, Set<WeeeTax> weeeTaxes) {
		this.countryId = countryId;
		this.iso2Code = iso2Code;
		this.iso3Code = iso3Code;
		this.weeeTaxes = weeeTaxes;
	}

	@Id
	@Column(name = "country_id", unique = true, nullable = false, length = 2)
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "iso2_code", length = 2)
	public String getIso2Code() {
		return this.iso2Code;
	}

	public void setIso2Code(String iso2Code) {
		this.iso2Code = iso2Code;
	}

	@Column(name = "iso3_code", length = 3)
	public String getIso3Code() {
		return this.iso3Code;
	}

	public void setIso3Code(String iso3Code) {
		this.iso3Code = iso3Code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "directoryCountry")
	public Set<WeeeTax> getWeeeTaxes() {
		return this.weeeTaxes;
	}

	public void setWeeeTaxes(Set<WeeeTax> weeeTaxes) {
		this.weeeTaxes = weeeTaxes;
	}

}
