package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LogSummaryType generated by hbm2java
 */
@Entity
@Table(name = "log_summary_type"
	, catalog = "magento")
public class LogSummaryType implements java.io.Serializable {

	private Short typeId;
	private String typeCode;
	private short period;
	private String periodType;

	public LogSummaryType() {
	}

	public LogSummaryType(short period, String periodType) {
		this.period = period;
		this.periodType = periodType;
	}

	public LogSummaryType(String typeCode, short period, String periodType) {
		this.typeCode = typeCode;
		this.period = period;
		this.periodType = periodType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "type_id", unique = true, nullable = false)
	public Short getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Short typeId) {
		this.typeId = typeId;
	}

	@Column(name = "type_code", length = 64)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "period", nullable = false)
	public short getPeriod() {
		return this.period;
	}

	public void setPeriod(short period) {
		this.period = period;
	}

	@Column(name = "period_type", nullable = false, length = 6)
	public String getPeriodType() {
		return this.periodType;
	}

	public void setPeriodType(String periodType) {
		this.periodType = periodType;
	}

}
