package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LogVisitorInfo generated by hbm2java
 */
@Entity
@Table(name = "log_visitor_info"
	, catalog = "magento")
public class LogVisitorInfo implements java.io.Serializable {

	private long visitorId;
	private String httpReferer;
	private String httpUserAgent;
	private String httpAcceptCharset;
	private String httpAcceptLanguage;
	private Long serverAddr;
	private Long remoteAddr;

	public LogVisitorInfo() {
	}

	public LogVisitorInfo(long visitorId) {
		this.visitorId = visitorId;
	}

	public LogVisitorInfo(long visitorId, String httpReferer, String httpUserAgent, String httpAcceptCharset, String httpAcceptLanguage, Long serverAddr, Long remoteAddr) {
		this.visitorId = visitorId;
		this.httpReferer = httpReferer;
		this.httpUserAgent = httpUserAgent;
		this.httpAcceptCharset = httpAcceptCharset;
		this.httpAcceptLanguage = httpAcceptLanguage;
		this.serverAddr = serverAddr;
		this.remoteAddr = remoteAddr;
	}

	@Id
	@Column(name = "visitor_id", unique = true, nullable = false)
	public long getVisitorId() {
		return this.visitorId;
	}

	public void setVisitorId(long visitorId) {
		this.visitorId = visitorId;
	}

	@Column(name = "http_referer")
	public String getHttpReferer() {
		return this.httpReferer;
	}

	public void setHttpReferer(String httpReferer) {
		this.httpReferer = httpReferer;
	}

	@Column(name = "http_user_agent")
	public String getHttpUserAgent() {
		return this.httpUserAgent;
	}

	public void setHttpUserAgent(String httpUserAgent) {
		this.httpUserAgent = httpUserAgent;
	}

	@Column(name = "http_accept_charset")
	public String getHttpAcceptCharset() {
		return this.httpAcceptCharset;
	}

	public void setHttpAcceptCharset(String httpAcceptCharset) {
		this.httpAcceptCharset = httpAcceptCharset;
	}

	@Column(name = "http_accept_language")
	public String getHttpAcceptLanguage() {
		return this.httpAcceptLanguage;
	}

	public void setHttpAcceptLanguage(String httpAcceptLanguage) {
		this.httpAcceptLanguage = httpAcceptLanguage;
	}

	@Column(name = "server_addr")
	public Long getServerAddr() {
		return this.serverAddr;
	}

	public void setServerAddr(Long serverAddr) {
		this.serverAddr = serverAddr;
	}

	@Column(name = "remote_addr")
	public Long getRemoteAddr() {
		return this.remoteAddr;
	}

	public void setRemoteAddr(Long remoteAddr) {
		this.remoteAddr = remoteAddr;
	}

}
