package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NewsletterTemplate generated by hbm2java
 */
@Entity
@Table(name = "newsletter_template"
	, catalog = "magento")
public class NewsletterTemplate implements java.io.Serializable {

	private Integer templateId;
	private String templateCode;
	private String templateText;
	private String templateTextPreprocessed;
	private String templateStyles;
	private Integer templateType;
	private String templateSubject;
	private String templateSenderName;
	private String templateSenderEmail;
	private Short templateActual;
	private Date addedAt;
	private Date modifiedAt;
	private Set<NewsletterQueue> newsletterQueues = new HashSet<NewsletterQueue>(0);

	public NewsletterTemplate() {
	}

	public NewsletterTemplate(String templateCode, String templateText, String templateTextPreprocessed, String templateStyles, Integer templateType, String templateSubject, String templateSenderName, String templateSenderEmail, Short templateActual, Date addedAt, Date modifiedAt, Set<NewsletterQueue> newsletterQueues) {
		this.templateCode = templateCode;
		this.templateText = templateText;
		this.templateTextPreprocessed = templateTextPreprocessed;
		this.templateStyles = templateStyles;
		this.templateType = templateType;
		this.templateSubject = templateSubject;
		this.templateSenderName = templateSenderName;
		this.templateSenderEmail = templateSenderEmail;
		this.templateActual = templateActual;
		this.addedAt = addedAt;
		this.modifiedAt = modifiedAt;
		this.newsletterQueues = newsletterQueues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "template_id", unique = true, nullable = false)
	public Integer getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Integer templateId) {
		this.templateId = templateId;
	}

	@Column(name = "template_code", length = 150)
	public String getTemplateCode() {
		return this.templateCode;
	}

	public void setTemplateCode(String templateCode) {
		this.templateCode = templateCode;
	}

	@Column(name = "template_text", length = 65535)
	public String getTemplateText() {
		return this.templateText;
	}

	public void setTemplateText(String templateText) {
		this.templateText = templateText;
	}

	@Column(name = "template_text_preprocessed", length = 65535)
	public String getTemplateTextPreprocessed() {
		return this.templateTextPreprocessed;
	}

	public void setTemplateTextPreprocessed(String templateTextPreprocessed) {
		this.templateTextPreprocessed = templateTextPreprocessed;
	}

	@Column(name = "template_styles", length = 65535)
	public String getTemplateStyles() {
		return this.templateStyles;
	}

	public void setTemplateStyles(String templateStyles) {
		this.templateStyles = templateStyles;
	}

	@Column(name = "template_type")
	public Integer getTemplateType() {
		return this.templateType;
	}

	public void setTemplateType(Integer templateType) {
		this.templateType = templateType;
	}

	@Column(name = "template_subject", length = 200)
	public String getTemplateSubject() {
		return this.templateSubject;
	}

	public void setTemplateSubject(String templateSubject) {
		this.templateSubject = templateSubject;
	}

	@Column(name = "template_sender_name", length = 200)
	public String getTemplateSenderName() {
		return this.templateSenderName;
	}

	public void setTemplateSenderName(String templateSenderName) {
		this.templateSenderName = templateSenderName;
	}

	@Column(name = "template_sender_email", length = 200)
	public String getTemplateSenderEmail() {
		return this.templateSenderEmail;
	}

	public void setTemplateSenderEmail(String templateSenderEmail) {
		this.templateSenderEmail = templateSenderEmail;
	}

	@Column(name = "template_actual")
	public Short getTemplateActual() {
		return this.templateActual;
	}

	public void setTemplateActual(Short templateActual) {
		this.templateActual = templateActual;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "added_at", length = 19)
	public Date getAddedAt() {
		return this.addedAt;
	}

	public void setAddedAt(Date addedAt) {
		this.addedAt = addedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_at", length = 19)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "newsletterTemplate")
	public Set<NewsletterQueue> getNewsletterQueues() {
		return this.newsletterQueues;
	}

	public void setNewsletterQueues(Set<NewsletterQueue> newsletterQueues) {
		this.newsletterQueues = newsletterQueues;
	}

}
