package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesFlatOrderAddress generated by hbm2java
 */
@Entity
@Table(name = "sales_flat_order_address"
	, catalog = "magento")
public class SalesFlatOrderAddress implements java.io.Serializable {

	private Integer entityId;
	private SalesFlatOrder salesFlatOrder;
	private Integer customerAddressId;
	private Integer quoteAddressId;
	private Integer regionId;
	private Integer customerId;
	private String fax;
	private String region;
	private String postcode;
	private String lastname;
	private String street;
	private String city;
	private String email;
	private String telephone;
	private String countryId;
	private String firstname;
	private String addressType;
	private String prefix;
	private String middlename;
	private String suffix;
	private String company;
	private String vatId;
	private Short vatIsValid;
	private String vatRequestId;
	private String vatRequestDate;
	private Short vatRequestSuccess;

	public SalesFlatOrderAddress() {
	}

	public SalesFlatOrderAddress(SalesFlatOrder salesFlatOrder, Integer customerAddressId, Integer quoteAddressId, Integer regionId, Integer customerId, String fax, String region, String postcode, String lastname, String street, String city, String email, String telephone, String countryId, String firstname, String addressType, String prefix, String middlename, String suffix, String company, String vatId, Short vatIsValid, String vatRequestId, String vatRequestDate, Short vatRequestSuccess) {
		this.salesFlatOrder = salesFlatOrder;
		this.customerAddressId = customerAddressId;
		this.quoteAddressId = quoteAddressId;
		this.regionId = regionId;
		this.customerId = customerId;
		this.fax = fax;
		this.region = region;
		this.postcode = postcode;
		this.lastname = lastname;
		this.street = street;
		this.city = city;
		this.email = email;
		this.telephone = telephone;
		this.countryId = countryId;
		this.firstname = firstname;
		this.addressType = addressType;
		this.prefix = prefix;
		this.middlename = middlename;
		this.suffix = suffix;
		this.company = company;
		this.vatId = vatId;
		this.vatIsValid = vatIsValid;
		this.vatRequestId = vatRequestId;
		this.vatRequestDate = vatRequestDate;
		this.vatRequestSuccess = vatRequestSuccess;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public SalesFlatOrder getSalesFlatOrder() {
		return this.salesFlatOrder;
	}

	public void setSalesFlatOrder(SalesFlatOrder salesFlatOrder) {
		this.salesFlatOrder = salesFlatOrder;
	}

	@Column(name = "customer_address_id")
	public Integer getCustomerAddressId() {
		return this.customerAddressId;
	}

	public void setCustomerAddressId(Integer customerAddressId) {
		this.customerAddressId = customerAddressId;
	}

	@Column(name = "quote_address_id")
	public Integer getQuoteAddressId() {
		return this.quoteAddressId;
	}

	public void setQuoteAddressId(Integer quoteAddressId) {
		this.quoteAddressId = quoteAddressId;
	}

	@Column(name = "region_id")
	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "fax")
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "region")
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "postcode")
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "lastname")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "street")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "country_id", length = 2)
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "address_type")
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "prefix")
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "middlename")
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "suffix")
	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	@Column(name = "company")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "vat_id", length = 65535)
	public String getVatId() {
		return this.vatId;
	}

	public void setVatId(String vatId) {
		this.vatId = vatId;
	}

	@Column(name = "vat_is_valid")
	public Short getVatIsValid() {
		return this.vatIsValid;
	}

	public void setVatIsValid(Short vatIsValid) {
		this.vatIsValid = vatIsValid;
	}

	@Column(name = "vat_request_id", length = 65535)
	public String getVatRequestId() {
		return this.vatRequestId;
	}

	public void setVatRequestId(String vatRequestId) {
		this.vatRequestId = vatRequestId;
	}

	@Column(name = "vat_request_date", length = 65535)
	public String getVatRequestDate() {
		return this.vatRequestDate;
	}

	public void setVatRequestDate(String vatRequestDate) {
		this.vatRequestDate = vatRequestDate;
	}

	@Column(name = "vat_request_success")
	public Short getVatRequestSuccess() {
		return this.vatRequestSuccess;
	}

	public void setVatRequestSuccess(Short vatRequestSuccess) {
		this.vatRequestSuccess = vatRequestSuccess;
	}

}
