package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SalesOrderStatusLabelId generated by hbm2java
 */
@Embeddable
public class SalesOrderStatusLabelId implements java.io.Serializable {

	private String status;
	private short storeId;

	public SalesOrderStatusLabelId() {
	}

	public SalesOrderStatusLabelId(String status, short storeId) {
		this.status = status;
		this.storeId = storeId;
	}

	@Column(name = "status", nullable = false, length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "store_id", nullable = false)
	public short getStoreId() {
		return this.storeId;
	}

	public void setStoreId(short storeId) {
		this.storeId = storeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalesOrderStatusLabelId))
			return false;
		SalesOrderStatusLabelId castOther = (SalesOrderStatusLabelId)other;

		return ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null && castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
			&& (this.getStoreId() == castOther.getStoreId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + this.getStoreId();
		return result;
	}

}
