package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesFlatQuotePayment generated by hbm2java
 */
@Entity
@Table(name = "sales_flat_quote_payment"
	, catalog = "magento")
public class SalesFlatQuotePayment implements java.io.Serializable {

	private Integer paymentId;
	private SalesFlatQuote salesFlatQuote;
	private Date createdAt;
	private Date updatedAt;
	private String method;
	private String ccType;
	private String ccNumberEnc;
	private String ccLast4;
	private String ccCidEnc;
	private String ccOwner;
	private Short ccExpMonth;
	private Short ccExpYear;
	private String ccSsOwner;
	private Short ccSsStartMonth;
	private Short ccSsStartYear;
	private String poNumber;
	private String additionalData;
	private String ccSsIssue;
	private String additionalInformation;
	private String paypalPayerId;
	private String paypalPayerStatus;
	private String paypalCorrelationId;

	public SalesFlatQuotePayment() {
	}

	public SalesFlatQuotePayment(SalesFlatQuote salesFlatQuote, Date createdAt, Date updatedAt) {
		this.salesFlatQuote = salesFlatQuote;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public SalesFlatQuotePayment(SalesFlatQuote salesFlatQuote, Date createdAt, Date updatedAt, String method, String ccType, String ccNumberEnc, String ccLast4, String ccCidEnc, String ccOwner, Short ccExpMonth, Short ccExpYear, String ccSsOwner, Short ccSsStartMonth, Short ccSsStartYear, String poNumber, String additionalData, String ccSsIssue, String additionalInformation, String paypalPayerId, String paypalPayerStatus, String paypalCorrelationId) {
		this.salesFlatQuote = salesFlatQuote;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.method = method;
		this.ccType = ccType;
		this.ccNumberEnc = ccNumberEnc;
		this.ccLast4 = ccLast4;
		this.ccCidEnc = ccCidEnc;
		this.ccOwner = ccOwner;
		this.ccExpMonth = ccExpMonth;
		this.ccExpYear = ccExpYear;
		this.ccSsOwner = ccSsOwner;
		this.ccSsStartMonth = ccSsStartMonth;
		this.ccSsStartYear = ccSsStartYear;
		this.poNumber = poNumber;
		this.additionalData = additionalData;
		this.ccSsIssue = ccSsIssue;
		this.additionalInformation = additionalInformation;
		this.paypalPayerId = paypalPayerId;
		this.paypalPayerStatus = paypalPayerStatus;
		this.paypalCorrelationId = paypalCorrelationId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "payment_id", unique = true, nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quote_id", nullable = false)
	public SalesFlatQuote getSalesFlatQuote() {
		return this.salesFlatQuote;
	}

	public void setSalesFlatQuote(SalesFlatQuote salesFlatQuote) {
		this.salesFlatQuote = salesFlatQuote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "method")
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "cc_type")
	public String getCcType() {
		return this.ccType;
	}

	public void setCcType(String ccType) {
		this.ccType = ccType;
	}

	@Column(name = "cc_number_enc")
	public String getCcNumberEnc() {
		return this.ccNumberEnc;
	}

	public void setCcNumberEnc(String ccNumberEnc) {
		this.ccNumberEnc = ccNumberEnc;
	}

	@Column(name = "cc_last4")
	public String getCcLast4() {
		return this.ccLast4;
	}

	public void setCcLast4(String ccLast4) {
		this.ccLast4 = ccLast4;
	}

	@Column(name = "cc_cid_enc")
	public String getCcCidEnc() {
		return this.ccCidEnc;
	}

	public void setCcCidEnc(String ccCidEnc) {
		this.ccCidEnc = ccCidEnc;
	}

	@Column(name = "cc_owner")
	public String getCcOwner() {
		return this.ccOwner;
	}

	public void setCcOwner(String ccOwner) {
		this.ccOwner = ccOwner;
	}

	@Column(name = "cc_exp_month")
	public Short getCcExpMonth() {
		return this.ccExpMonth;
	}

	public void setCcExpMonth(Short ccExpMonth) {
		this.ccExpMonth = ccExpMonth;
	}

	@Column(name = "cc_exp_year")
	public Short getCcExpYear() {
		return this.ccExpYear;
	}

	public void setCcExpYear(Short ccExpYear) {
		this.ccExpYear = ccExpYear;
	}

	@Column(name = "cc_ss_owner")
	public String getCcSsOwner() {
		return this.ccSsOwner;
	}

	public void setCcSsOwner(String ccSsOwner) {
		this.ccSsOwner = ccSsOwner;
	}

	@Column(name = "cc_ss_start_month")
	public Short getCcSsStartMonth() {
		return this.ccSsStartMonth;
	}

	public void setCcSsStartMonth(Short ccSsStartMonth) {
		this.ccSsStartMonth = ccSsStartMonth;
	}

	@Column(name = "cc_ss_start_year")
	public Short getCcSsStartYear() {
		return this.ccSsStartYear;
	}

	public void setCcSsStartYear(Short ccSsStartYear) {
		this.ccSsStartYear = ccSsStartYear;
	}

	@Column(name = "po_number")
	public String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Column(name = "additional_data", length = 65535)
	public String getAdditionalData() {
		return this.additionalData;
	}

	public void setAdditionalData(String additionalData) {
		this.additionalData = additionalData;
	}

	@Column(name = "cc_ss_issue")
	public String getCcSsIssue() {
		return this.ccSsIssue;
	}

	public void setCcSsIssue(String ccSsIssue) {
		this.ccSsIssue = ccSsIssue;
	}

	@Column(name = "additional_information", length = 65535)
	public String getAdditionalInformation() {
		return this.additionalInformation;
	}

	public void setAdditionalInformation(String additionalInformation) {
		this.additionalInformation = additionalInformation;
	}

	@Column(name = "paypal_payer_id")
	public String getPaypalPayerId() {
		return this.paypalPayerId;
	}

	public void setPaypalPayerId(String paypalPayerId) {
		this.paypalPayerId = paypalPayerId;
	}

	@Column(name = "paypal_payer_status")
	public String getPaypalPayerStatus() {
		return this.paypalPayerStatus;
	}

	public void setPaypalPayerStatus(String paypalPayerStatus) {
		this.paypalPayerStatus = paypalPayerStatus;
	}

	@Column(name = "paypal_correlation_id")
	public String getPaypalCorrelationId() {
		return this.paypalCorrelationId;
	}

	public void setPaypalCorrelationId(String paypalCorrelationId) {
		this.paypalCorrelationId = paypalCorrelationId;
	}

}
