package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SendfriendLog generated by hbm2java
 */
@Entity
@Table(name = "sendfriend_log"
	, catalog = "magento")
public class SendfriendLog implements java.io.Serializable {

	private Integer logId;
	private long ip;
	private int time;
	private short websiteId;

	public SendfriendLog() {
	}

	public SendfriendLog(long ip, int time, short websiteId) {
		this.ip = ip;
		this.time = time;
		this.websiteId = websiteId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "log_id", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "ip", nullable = false)
	public long getIp() {
		return this.ip;
	}

	public void setIp(long ip) {
		this.ip = ip;
	}

	@Column(name = "time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	@Column(name = "website_id", nullable = false)
	public short getWebsiteId() {
		return this.websiteId;
	}

	public void setWebsiteId(short websiteId) {
		this.websiteId = websiteId;
	}

}
