package com.naver.mage4j.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * XmlconnectConfigDataId generated by hbm2java
 */
@Embeddable
public class XmlconnectConfigDataId implements java.io.Serializable {

	private short applicationId;
	private String category;
	private String path;
	private String value;

	public XmlconnectConfigDataId() {
	}

	public XmlconnectConfigDataId(short applicationId, String category, String path, String value) {
		this.applicationId = applicationId;
		this.category = category;
		this.path = path;
		this.value = value;
	}

	@Column(name = "application_id", nullable = false)
	public short getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(short applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "category", nullable = false, length = 60)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "path", nullable = false, length = 250)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "value", nullable = false, length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof XmlconnectConfigDataId))
			return false;
		XmlconnectConfigDataId castOther = (XmlconnectConfigDataId)other;

		return (this.getApplicationId() == castOther.getApplicationId())
			&& ((this.getCategory() == castOther.getCategory()) || (this.getCategory() != null && castOther.getCategory() != null && this.getCategory().equals(castOther.getCategory())))
			&& ((this.getPath() == castOther.getPath()) || (this.getPath() != null && castOther.getPath() != null && this.getPath().equals(castOther.getPath())))
			&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null && castOther.getValue() != null && this.getValue().equals(castOther.getValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getApplicationId();
		result = 37 * result + (getCategory() == null ? 0 : this.getCategory().hashCode());
		result = 37 * result + (getPath() == null ? 0 : this.getPath().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		return result;
	}

}
