package com.naver.mage4j.core.mage.core.model.resource.design;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.*;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.naver.mage4j.core.mage.core.model.resource.store.Store;

/**
 * DesignChange generated by hbm2java
 */
@Entity
@Table(name = "design_change"
	, catalog = "magento")
public class DesignChange implements java.io.Serializable {

	private Integer designChangeId;
	private Store store;
	private String design;
	private Date dateFrom;
	private Date dateTo;

	public DesignChange() {
	}

	public DesignChange(Store coreStore) {
		this.store = coreStore;
	}

	public DesignChange(Store coreStore, String design, Date dateFrom, Date dateTo) {
		this.store = coreStore;
		this.design = design;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "design_change_id", unique = true, nullable = false)
	public Integer getDesignChangeId() {
		return this.designChangeId;
	}

	public void setDesignChangeId(Integer designChangeId) {
		this.designChangeId = designChangeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "design")
	public String getDesign() {
		return this.design;
	}

	public void setDesign(String design) {
		this.design = design;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_from", length = 10)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_to", length = 10)
	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	private transient String _package;
	private transient String theme;

	@Transient
	public String getPackage() {
		return _package;
	}

	@Transient
	public String getTheme() {
		return theme;
	}
}
