package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatalogProductIndexPriceDownlodTmp generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_index_price_downlod_tmp"
	, catalog = "magento")
public class CatalogProductIndexPriceDownlodTmp implements java.io.Serializable {

	private CatalogProductIndexPriceDownlodTmpId id;
	private BigDecimal minPrice;
	private BigDecimal maxPrice;

	public CatalogProductIndexPriceDownlodTmp() {
	}

	public CatalogProductIndexPriceDownlodTmp(CatalogProductIndexPriceDownlodTmpId id, BigDecimal minPrice, BigDecimal maxPrice) {
		this.id = id;
		this.minPrice = minPrice;
		this.maxPrice = maxPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "entityId", column = @Column(name = "entity_id", nullable = false)),
		@AttributeOverride(name = "customerGroupId", column = @Column(name = "customer_group_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false))})
	public CatalogProductIndexPriceDownlodTmpId getId() {
		return this.id;
	}

	public void setId(CatalogProductIndexPriceDownlodTmpId id) {
		this.id = id;
	}

	@Column(name = "min_price", nullable = false, precision = 12, scale = 4)
	public BigDecimal getMinPrice() {
		return this.minPrice;
	}

	public void setMinPrice(BigDecimal minPrice) {
		this.minPrice = minPrice;
	}

	@Column(name = "max_price", nullable = false, precision = 12, scale = 4)
	public BigDecimal getMaxPrice() {
		return this.maxPrice;
	}

	public void setMaxPrice(BigDecimal maxPrice) {
		this.maxPrice = maxPrice;
	}

}
