package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.naver.mage4j.core.mage.core.model.resource.website.Website;

/**
 * CatalogProductBundleSelectionPrice generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_bundle_selection_price"
	, catalog = "magento")
public class CatalogProductBundleSelectionPrice implements java.io.Serializable {

	private CatalogProductBundleSelectionPriceId id;
	private Website coreWebsite;
	private CatalogProductBundleSelection catalogProductBundleSelection;
	private short selectionPriceType;
	private BigDecimal selectionPriceValue;

	public CatalogProductBundleSelectionPrice() {
	}

	public CatalogProductBundleSelectionPrice(CatalogProductBundleSelectionPriceId id, Website coreWebsite, CatalogProductBundleSelection catalogProductBundleSelection, short selectionPriceType, BigDecimal selectionPriceValue) {
		this.id = id;
		this.coreWebsite = coreWebsite;
		this.catalogProductBundleSelection = catalogProductBundleSelection;
		this.selectionPriceType = selectionPriceType;
		this.selectionPriceValue = selectionPriceValue;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "selectionId", column = @Column(name = "selection_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false))})
	public CatalogProductBundleSelectionPriceId getId() {
		return this.id;
	}

	public void setId(CatalogProductBundleSelectionPriceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "website_id", nullable = false, insertable = false, updatable = false)
	public Website getCoreWebsite() {
		return this.coreWebsite;
	}

	public void setCoreWebsite(Website coreWebsite) {
		this.coreWebsite = coreWebsite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "selection_id", nullable = false, insertable = false, updatable = false)
	public CatalogProductBundleSelection getCatalogProductBundleSelection() {
		return this.catalogProductBundleSelection;
	}

	public void setCatalogProductBundleSelection(CatalogProductBundleSelection catalogProductBundleSelection) {
		this.catalogProductBundleSelection = catalogProductBundleSelection;
	}

	@Column(name = "selection_price_type", nullable = false)
	public short getSelectionPriceType() {
		return this.selectionPriceType;
	}

	public void setSelectionPriceType(short selectionPriceType) {
		this.selectionPriceType = selectionPriceType;
	}

	@Column(name = "selection_price_value", nullable = false, precision = 12, scale = 4)
	public BigDecimal getSelectionPriceValue() {
		return this.selectionPriceValue;
	}

	public void setSelectionPriceValue(BigDecimal selectionPriceValue) {
		this.selectionPriceValue = selectionPriceValue;
	}

}
