package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatalogCategoryProductIndexIdx generated by hbm2java
 */
@Entity
@Table(name = "catalog_category_product_index_idx"
	, catalog = "magento")
public class CatalogCategoryProductIndexIdx implements java.io.Serializable {

	private CatalogCategoryProductIndexIdxId id;

	public CatalogCategoryProductIndexIdx() {
	}

	public CatalogCategoryProductIndexIdx(CatalogCategoryProductIndexIdxId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)),
		@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
		@AttributeOverride(name = "position", column = @Column(name = "position", nullable = false)),
		@AttributeOverride(name = "isParent", column = @Column(name = "is_parent", nullable = false)),
		@AttributeOverride(name = "storeId", column = @Column(name = "store_id", nullable = false)),
		@AttributeOverride(name = "visibility", column = @Column(name = "visibility", nullable = false))})
	public CatalogCategoryProductIndexIdxId getId() {
		return this.id;
	}

	public void setId(CatalogCategoryProductIndexIdxId id) {
		this.id = id;
	}

}
