package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.naver.mage4j.core.mage.core.model.resource.store.Store;

/**
 * CatalogProductIndexEav generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_index_eav"
	, catalog = "magento")
public class CatalogProductIndexEav implements java.io.Serializable {

	private CatalogProductIndexEavId id;
	private CatalogProductEntity catalogProductEntity;
	private EavAttribute eavAttribute;
	private Store coreStore;

	public CatalogProductIndexEav() {
	}

	public CatalogProductIndexEav(CatalogProductIndexEavId id, CatalogProductEntity catalogProductEntity, EavAttribute eavAttribute, Store coreStore) {
		this.id = id;
		this.catalogProductEntity = catalogProductEntity;
		this.eavAttribute = eavAttribute;
		this.coreStore = coreStore;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "entityId", column = @Column(name = "entity_id", nullable = false)),
		@AttributeOverride(name = "attributeId", column = @Column(name = "attribute_id", nullable = false)),
		@AttributeOverride(name = "storeId", column = @Column(name = "store_id", nullable = false)),
		@AttributeOverride(name = "value", column = @Column(name = "value", nullable = false))})
	public CatalogProductIndexEavId getId() {
		return this.id;
	}

	public void setId(CatalogProductIndexEavId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entity_id", nullable = false, insertable = false, updatable = false)
	public CatalogProductEntity getCatalogProductEntity() {
		return this.catalogProductEntity;
	}

	public void setCatalogProductEntity(CatalogProductEntity catalogProductEntity) {
		this.catalogProductEntity = catalogProductEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_id", nullable = false, insertable = false, updatable = false)
	public EavAttribute getEavAttribute() {
		return this.eavAttribute;
	}

	public void setEavAttribute(EavAttribute eavAttribute) {
		this.eavAttribute = eavAttribute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false, insertable = false, updatable = false)
	public Store getCoreStore() {
		return this.coreStore;
	}

	public void setCoreStore(Store coreStore) {
		this.coreStore = coreStore;
	}

}
