package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.naver.mage4j.core.mage.core.model.resource.store.Store;

/**
 * CoreVariableValue generated by hbm2java
 */
@Entity
@Table(name = "core_variable_value"
	, catalog = "magento"
	, uniqueConstraints = @UniqueConstraint(columnNames = {"variable_id", "store_id"}))
public class CoreVariableValue implements java.io.Serializable {

	private Integer valueId;
	private CoreVariable coreVariable;
	private Store coreStore;
	private String plainValue;
	private String htmlValue;

	public CoreVariableValue() {
	}

	public CoreVariableValue(CoreVariable coreVariable, Store coreStore) {
		this.coreVariable = coreVariable;
		this.coreStore = coreStore;
	}

	public CoreVariableValue(CoreVariable coreVariable, Store coreStore, String plainValue, String htmlValue) {
		this.coreVariable = coreVariable;
		this.coreStore = coreStore;
		this.plainValue = plainValue;
		this.htmlValue = htmlValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "value_id", unique = true, nullable = false)
	public Integer getValueId() {
		return this.valueId;
	}

	public void setValueId(Integer valueId) {
		this.valueId = valueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "variable_id", nullable = false)
	public CoreVariable getCoreVariable() {
		return this.coreVariable;
	}

	public void setCoreVariable(CoreVariable coreVariable) {
		this.coreVariable = coreVariable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	public Store getCoreStore() {
		return this.coreStore;
	}

	public void setCoreStore(Store coreStore) {
		this.coreStore = coreStore;
	}

	@Column(name = "plain_value", length = 65535, columnDefinition = "TEXT")
	public String getPlainValue() {
		return this.plainValue;
	}

	public void setPlainValue(String plainValue) {
		this.plainValue = plainValue;
	}

	@Column(name = "html_value", length = 65535, columnDefinition = "TEXT")
	public String getHtmlValue() {
		return this.htmlValue;
	}

	public void setHtmlValue(String htmlValue) {
		this.htmlValue = htmlValue;
	}

}
