package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.naver.mage4j.core.mage.core.model.resource.website.Website;

/**
 * CustomerEavAttributeWebsite generated by hbm2java
 */
@Entity
@Table(name = "customer_eav_attribute_website"
	, catalog = "magento")
public class CustomerEavAttributeWebsite implements java.io.Serializable {

	private CustomerEavAttributeWebsiteId id;
	private Website coreWebsite;
	private EavAttribute eavAttribute;
	private Short isVisible;
	private Short isRequired;
	private String defaultValue;
	private Short multilineCount;

	public CustomerEavAttributeWebsite() {
	}

	public CustomerEavAttributeWebsite(CustomerEavAttributeWebsiteId id, Website coreWebsite, EavAttribute eavAttribute) {
		this.id = id;
		this.coreWebsite = coreWebsite;
		this.eavAttribute = eavAttribute;
	}

	public CustomerEavAttributeWebsite(CustomerEavAttributeWebsiteId id, Website coreWebsite, EavAttribute eavAttribute, Short isVisible, Short isRequired, String defaultValue, Short multilineCount) {
		this.id = id;
		this.coreWebsite = coreWebsite;
		this.eavAttribute = eavAttribute;
		this.isVisible = isVisible;
		this.isRequired = isRequired;
		this.defaultValue = defaultValue;
		this.multilineCount = multilineCount;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "attributeId", column = @Column(name = "attribute_id", nullable = false)),
		@AttributeOverride(name = "websiteId", column = @Column(name = "website_id", nullable = false))})
	public CustomerEavAttributeWebsiteId getId() {
		return this.id;
	}

	public void setId(CustomerEavAttributeWebsiteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "website_id", nullable = false, insertable = false, updatable = false)
	public Website getCoreWebsite() {
		return this.coreWebsite;
	}

	public void setCoreWebsite(Website coreWebsite) {
		this.coreWebsite = coreWebsite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_id", nullable = false, insertable = false, updatable = false)
	public EavAttribute getEavAttribute() {
		return this.eavAttribute;
	}

	public void setEavAttribute(EavAttribute eavAttribute) {
		this.eavAttribute = eavAttribute;
	}

	@Column(name = "is_visible")
	public Short getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(Short isVisible) {
		this.isVisible = isVisible;
	}

	@Column(name = "is_required")
	public Short getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(Short isRequired) {
		this.isRequired = isRequired;
	}

	@Column(name = "default_value", length = 65535, columnDefinition = "TEXT")
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Column(name = "multiline_count")
	public Short getMultilineCount() {
		return this.multilineCount;
	}

	public void setMultilineCount(Short multilineCount) {
		this.multilineCount = multilineCount;
	}

}
