package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerFormAttributeId generated by hbm2java
 */
@Embeddable
public class CustomerFormAttributeId implements java.io.Serializable {

	private String formCode;
	private short attributeId;

	public CustomerFormAttributeId() {
	}

	public CustomerFormAttributeId(String formCode, short attributeId) {
		this.formCode = formCode;
		this.attributeId = attributeId;
	}

	@Column(name = "form_code", nullable = false, length = 32)
	public String getFormCode() {
		return this.formCode;
	}

	public void setFormCode(String formCode) {
		this.formCode = formCode;
	}

	@Column(name = "attribute_id", nullable = false)
	public short getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(short attributeId) {
		this.attributeId = attributeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomerFormAttributeId))
			return false;
		CustomerFormAttributeId castOther = (CustomerFormAttributeId)other;

		return ((this.getFormCode() == castOther.getFormCode()) || (this.getFormCode() != null && castOther.getFormCode() != null && this.getFormCode().equals(castOther.getFormCode())))
			&& (this.getAttributeId() == castOther.getAttributeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFormCode() == null ? 0 : this.getFormCode().hashCode());
		result = 37 * result + this.getAttributeId();
		return result;
	}

}
