package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.naver.mage4j.core.mage.core.model.resource.store.Store;

/**
 * RatingTitle generated by hbm2java
 */
@Entity
@Table(name = "rating_title"
	, catalog = "magento")
public class RatingTitle implements java.io.Serializable {

	private RatingTitleId id;
	private Rating rating;
	private Store coreStore;
	private String value;

	public RatingTitle() {
	}

	public RatingTitle(RatingTitleId id, Rating rating, Store coreStore, String value) {
		this.id = id;
		this.rating = rating;
		this.coreStore = coreStore;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "ratingId", column = @Column(name = "rating_id", nullable = false)),
		@AttributeOverride(name = "storeId", column = @Column(name = "store_id", nullable = false))})
	public RatingTitleId getId() {
		return this.id;
	}

	public void setId(RatingTitleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rating_id", nullable = false, insertable = false, updatable = false)
	public Rating getRating() {
		return this.rating;
	}

	public void setRating(Rating rating) {
		this.rating = rating;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false, insertable = false, updatable = false)
	public Store getCoreStore() {
		return this.coreStore;
	}

	public void setCoreStore(Store coreStore) {
		this.coreStore = coreStore;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
