package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.naver.mage4j.core.mage.core.model.resource.store.Store;

/**
 * SalesBestsellersAggregatedDaily generated by hbm2java
 */
@Entity
@Table(name = "sales_bestsellers_aggregated_daily"
	, catalog = "magento"
	, uniqueConstraints = @UniqueConstraint(columnNames = {"period", "store_id", "product_id"}))
public class SalesBestsellersAggregatedDaily implements java.io.Serializable {

	private Integer id;
	private Store coreStore;
	private CatalogProductEntity catalogProductEntity;
	private Date period;
	private String productName;
	private BigDecimal productPrice;
	private BigDecimal qtyOrdered;
	private short ratingPos;

	public SalesBestsellersAggregatedDaily() {
	}

	public SalesBestsellersAggregatedDaily(BigDecimal productPrice, BigDecimal qtyOrdered, short ratingPos) {
		this.productPrice = productPrice;
		this.qtyOrdered = qtyOrdered;
		this.ratingPos = ratingPos;
	}

	public SalesBestsellersAggregatedDaily(Store coreStore, CatalogProductEntity catalogProductEntity, Date period, String productName, BigDecimal productPrice, BigDecimal qtyOrdered, short ratingPos) {
		this.coreStore = coreStore;
		this.catalogProductEntity = catalogProductEntity;
		this.period = period;
		this.productName = productName;
		this.productPrice = productPrice;
		this.qtyOrdered = qtyOrdered;
		this.ratingPos = ratingPos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getCoreStore() {
		return this.coreStore;
	}

	public void setCoreStore(Store coreStore) {
		this.coreStore = coreStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public CatalogProductEntity getCatalogProductEntity() {
		return this.catalogProductEntity;
	}

	public void setCatalogProductEntity(CatalogProductEntity catalogProductEntity) {
		this.catalogProductEntity = catalogProductEntity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "period", length = 10)
	public Date getPeriod() {
		return this.period;
	}

	public void setPeriod(Date period) {
		this.period = period;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_price", nullable = false, precision = 12, scale = 4)
	public BigDecimal getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "qty_ordered", nullable = false, precision = 12, scale = 4)
	public BigDecimal getQtyOrdered() {
		return this.qtyOrdered;
	}

	public void setQtyOrdered(BigDecimal qtyOrdered) {
		this.qtyOrdered = qtyOrdered;
	}

	@Column(name = "rating_pos", nullable = false)
	public short getRatingPos() {
		return this.ratingPos;
	}

	public void setRatingPos(short ratingPos) {
		this.ratingPos = ratingPos;
	}

}
