package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesFlatInvoiceItem generated by hbm2java
 */
@Entity
@Table(name = "sales_flat_invoice_item"
	, catalog = "magento")
public class SalesFlatInvoiceItem implements java.io.Serializable {

	private Integer entityId;
	private SalesFlatInvoice salesFlatInvoice;
	private BigDecimal basePrice;
	private BigDecimal taxAmount;
	private BigDecimal baseRowTotal;
	private BigDecimal discountAmount;
	private BigDecimal rowTotal;
	private BigDecimal baseDiscountAmount;
	private BigDecimal priceInclTax;
	private BigDecimal baseTaxAmount;
	private BigDecimal basePriceInclTax;
	private BigDecimal qty;
	private BigDecimal baseCost;
	private BigDecimal price;
	private BigDecimal baseRowTotalInclTax;
	private BigDecimal rowTotalInclTax;
	private Integer productId;
	private Integer orderItemId;
	private String additionalData;
	private String description;
	private String sku;
	private String name;
	private BigDecimal hiddenTaxAmount;
	private BigDecimal baseHiddenTaxAmount;
	private BigDecimal baseWeeeTaxAppliedAmount;
	private BigDecimal baseWeeeTaxAppliedRowAmnt;
	private BigDecimal weeeTaxAppliedAmount;
	private BigDecimal weeeTaxAppliedRowAmount;
	private String weeeTaxApplied;
	private BigDecimal weeeTaxDisposition;
	private BigDecimal weeeTaxRowDisposition;
	private BigDecimal baseWeeeTaxDisposition;
	private BigDecimal baseWeeeTaxRowDisposition;

	public SalesFlatInvoiceItem() {
	}

	public SalesFlatInvoiceItem(SalesFlatInvoice salesFlatInvoice) {
		this.salesFlatInvoice = salesFlatInvoice;
	}

	public SalesFlatInvoiceItem(SalesFlatInvoice salesFlatInvoice, BigDecimal basePrice, BigDecimal taxAmount, BigDecimal baseRowTotal, BigDecimal discountAmount, BigDecimal rowTotal, BigDecimal baseDiscountAmount, BigDecimal priceInclTax, BigDecimal baseTaxAmount, BigDecimal basePriceInclTax, BigDecimal qty, BigDecimal baseCost, BigDecimal price, BigDecimal baseRowTotalInclTax, BigDecimal rowTotalInclTax, Integer productId, Integer orderItemId, String additionalData, String description,
		String sku, String name, BigDecimal hiddenTaxAmount, BigDecimal baseHiddenTaxAmount, BigDecimal baseWeeeTaxAppliedAmount, BigDecimal baseWeeeTaxAppliedRowAmnt, BigDecimal weeeTaxAppliedAmount, BigDecimal weeeTaxAppliedRowAmount, String weeeTaxApplied, BigDecimal weeeTaxDisposition, BigDecimal weeeTaxRowDisposition, BigDecimal baseWeeeTaxDisposition, BigDecimal baseWeeeTaxRowDisposition) {
		this.salesFlatInvoice = salesFlatInvoice;
		this.basePrice = basePrice;
		this.taxAmount = taxAmount;
		this.baseRowTotal = baseRowTotal;
		this.discountAmount = discountAmount;
		this.rowTotal = rowTotal;
		this.baseDiscountAmount = baseDiscountAmount;
		this.priceInclTax = priceInclTax;
		this.baseTaxAmount = baseTaxAmount;
		this.basePriceInclTax = basePriceInclTax;
		this.qty = qty;
		this.baseCost = baseCost;
		this.price = price;
		this.baseRowTotalInclTax = baseRowTotalInclTax;
		this.rowTotalInclTax = rowTotalInclTax;
		this.productId = productId;
		this.orderItemId = orderItemId;
		this.additionalData = additionalData;
		this.description = description;
		this.sku = sku;
		this.name = name;
		this.hiddenTaxAmount = hiddenTaxAmount;
		this.baseHiddenTaxAmount = baseHiddenTaxAmount;
		this.baseWeeeTaxAppliedAmount = baseWeeeTaxAppliedAmount;
		this.baseWeeeTaxAppliedRowAmnt = baseWeeeTaxAppliedRowAmnt;
		this.weeeTaxAppliedAmount = weeeTaxAppliedAmount;
		this.weeeTaxAppliedRowAmount = weeeTaxAppliedRowAmount;
		this.weeeTaxApplied = weeeTaxApplied;
		this.weeeTaxDisposition = weeeTaxDisposition;
		this.weeeTaxRowDisposition = weeeTaxRowDisposition;
		this.baseWeeeTaxDisposition = baseWeeeTaxDisposition;
		this.baseWeeeTaxRowDisposition = baseWeeeTaxRowDisposition;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public SalesFlatInvoice getSalesFlatInvoice() {
		return this.salesFlatInvoice;
	}

	public void setSalesFlatInvoice(SalesFlatInvoice salesFlatInvoice) {
		this.salesFlatInvoice = salesFlatInvoice;
	}

	@Column(name = "base_price", precision = 12, scale = 4)
	public BigDecimal getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(BigDecimal basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "tax_amount", precision = 12, scale = 4)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "base_row_total", precision = 12, scale = 4)
	public BigDecimal getBaseRowTotal() {
		return this.baseRowTotal;
	}

	public void setBaseRowTotal(BigDecimal baseRowTotal) {
		this.baseRowTotal = baseRowTotal;
	}

	@Column(name = "discount_amount", precision = 12, scale = 4)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "row_total", precision = 12, scale = 4)
	public BigDecimal getRowTotal() {
		return this.rowTotal;
	}

	public void setRowTotal(BigDecimal rowTotal) {
		this.rowTotal = rowTotal;
	}

	@Column(name = "base_discount_amount", precision = 12, scale = 4)
	public BigDecimal getBaseDiscountAmount() {
		return this.baseDiscountAmount;
	}

	public void setBaseDiscountAmount(BigDecimal baseDiscountAmount) {
		this.baseDiscountAmount = baseDiscountAmount;
	}

	@Column(name = "price_incl_tax", precision = 12, scale = 4)
	public BigDecimal getPriceInclTax() {
		return this.priceInclTax;
	}

	public void setPriceInclTax(BigDecimal priceInclTax) {
		this.priceInclTax = priceInclTax;
	}

	@Column(name = "base_tax_amount", precision = 12, scale = 4)
	public BigDecimal getBaseTaxAmount() {
		return this.baseTaxAmount;
	}

	public void setBaseTaxAmount(BigDecimal baseTaxAmount) {
		this.baseTaxAmount = baseTaxAmount;
	}

	@Column(name = "base_price_incl_tax", precision = 12, scale = 4)
	public BigDecimal getBasePriceInclTax() {
		return this.basePriceInclTax;
	}

	public void setBasePriceInclTax(BigDecimal basePriceInclTax) {
		this.basePriceInclTax = basePriceInclTax;
	}

	@Column(name = "qty", precision = 12, scale = 4)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "base_cost", precision = 12, scale = 4)
	public BigDecimal getBaseCost() {
		return this.baseCost;
	}

	public void setBaseCost(BigDecimal baseCost) {
		this.baseCost = baseCost;
	}

	@Column(name = "price", precision = 12, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "base_row_total_incl_tax", precision = 12, scale = 4)
	public BigDecimal getBaseRowTotalInclTax() {
		return this.baseRowTotalInclTax;
	}

	public void setBaseRowTotalInclTax(BigDecimal baseRowTotalInclTax) {
		this.baseRowTotalInclTax = baseRowTotalInclTax;
	}

	@Column(name = "row_total_incl_tax", precision = 12, scale = 4)
	public BigDecimal getRowTotalInclTax() {
		return this.rowTotalInclTax;
	}

	public void setRowTotalInclTax(BigDecimal rowTotalInclTax) {
		this.rowTotalInclTax = rowTotalInclTax;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "order_item_id")
	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Column(name = "additional_data", length = 65535, columnDefinition = "TEXT")
	public String getAdditionalData() {
		return this.additionalData;
	}

	public void setAdditionalData(String additionalData) {
		this.additionalData = additionalData;
	}

	@Column(name = "description", length = 65535, columnDefinition = "TEXT")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "sku")
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "hidden_tax_amount", precision = 12, scale = 4)
	public BigDecimal getHiddenTaxAmount() {
		return this.hiddenTaxAmount;
	}

	public void setHiddenTaxAmount(BigDecimal hiddenTaxAmount) {
		this.hiddenTaxAmount = hiddenTaxAmount;
	}

	@Column(name = "base_hidden_tax_amount", precision = 12, scale = 4)
	public BigDecimal getBaseHiddenTaxAmount() {
		return this.baseHiddenTaxAmount;
	}

	public void setBaseHiddenTaxAmount(BigDecimal baseHiddenTaxAmount) {
		this.baseHiddenTaxAmount = baseHiddenTaxAmount;
	}

	@Column(name = "base_weee_tax_applied_amount", precision = 12, scale = 4)
	public BigDecimal getBaseWeeeTaxAppliedAmount() {
		return this.baseWeeeTaxAppliedAmount;
	}

	public void setBaseWeeeTaxAppliedAmount(BigDecimal baseWeeeTaxAppliedAmount) {
		this.baseWeeeTaxAppliedAmount = baseWeeeTaxAppliedAmount;
	}

	@Column(name = "base_weee_tax_applied_row_amnt", precision = 12, scale = 4)
	public BigDecimal getBaseWeeeTaxAppliedRowAmnt() {
		return this.baseWeeeTaxAppliedRowAmnt;
	}

	public void setBaseWeeeTaxAppliedRowAmnt(BigDecimal baseWeeeTaxAppliedRowAmnt) {
		this.baseWeeeTaxAppliedRowAmnt = baseWeeeTaxAppliedRowAmnt;
	}

	@Column(name = "weee_tax_applied_amount", precision = 12, scale = 4)
	public BigDecimal getWeeeTaxAppliedAmount() {
		return this.weeeTaxAppliedAmount;
	}

	public void setWeeeTaxAppliedAmount(BigDecimal weeeTaxAppliedAmount) {
		this.weeeTaxAppliedAmount = weeeTaxAppliedAmount;
	}

	@Column(name = "weee_tax_applied_row_amount", precision = 12, scale = 4)
	public BigDecimal getWeeeTaxAppliedRowAmount() {
		return this.weeeTaxAppliedRowAmount;
	}

	public void setWeeeTaxAppliedRowAmount(BigDecimal weeeTaxAppliedRowAmount) {
		this.weeeTaxAppliedRowAmount = weeeTaxAppliedRowAmount;
	}

	@Column(name = "weee_tax_applied", length = 65535, columnDefinition = "TEXT")
	public String getWeeeTaxApplied() {
		return this.weeeTaxApplied;
	}

	public void setWeeeTaxApplied(String weeeTaxApplied) {
		this.weeeTaxApplied = weeeTaxApplied;
	}

	@Column(name = "weee_tax_disposition", precision = 12, scale = 4)
	public BigDecimal getWeeeTaxDisposition() {
		return this.weeeTaxDisposition;
	}

	public void setWeeeTaxDisposition(BigDecimal weeeTaxDisposition) {
		this.weeeTaxDisposition = weeeTaxDisposition;
	}

	@Column(name = "weee_tax_row_disposition", precision = 12, scale = 4)
	public BigDecimal getWeeeTaxRowDisposition() {
		return this.weeeTaxRowDisposition;
	}

	public void setWeeeTaxRowDisposition(BigDecimal weeeTaxRowDisposition) {
		this.weeeTaxRowDisposition = weeeTaxRowDisposition;
	}

	@Column(name = "base_weee_tax_disposition", precision = 12, scale = 4)
	public BigDecimal getBaseWeeeTaxDisposition() {
		return this.baseWeeeTaxDisposition;
	}

	public void setBaseWeeeTaxDisposition(BigDecimal baseWeeeTaxDisposition) {
		this.baseWeeeTaxDisposition = baseWeeeTaxDisposition;
	}

	@Column(name = "base_weee_tax_row_disposition", precision = 12, scale = 4)
	public BigDecimal getBaseWeeeTaxRowDisposition() {
		return this.baseWeeeTaxRowDisposition;
	}

	public void setBaseWeeeTaxRowDisposition(BigDecimal baseWeeeTaxRowDisposition) {
		this.baseWeeeTaxRowDisposition = baseWeeeTaxRowDisposition;
	}

}
