package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesruleCouponUsage generated by hbm2java
 */
@Entity
@Table(name = "salesrule_coupon_usage"
	, catalog = "magento")
public class SalesruleCouponUsage implements java.io.Serializable {

	private SalesruleCouponUsageId id;
	private SalesruleCoupon salesruleCoupon;
	private CustomerEntity customerEntity;
	private int timesUsed;

	public SalesruleCouponUsage() {
	}

	public SalesruleCouponUsage(SalesruleCouponUsageId id, SalesruleCoupon salesruleCoupon, CustomerEntity customerEntity, int timesUsed) {
		this.id = id;
		this.salesruleCoupon = salesruleCoupon;
		this.customerEntity = customerEntity;
		this.timesUsed = timesUsed;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "couponId", column = @Column(name = "coupon_id", nullable = false)),
		@AttributeOverride(name = "customerId", column = @Column(name = "customer_id", nullable = false))})
	public SalesruleCouponUsageId getId() {
		return this.id;
	}

	public void setId(SalesruleCouponUsageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", nullable = false, insertable = false, updatable = false)
	public SalesruleCoupon getSalesruleCoupon() {
		return this.salesruleCoupon;
	}

	public void setSalesruleCoupon(SalesruleCoupon salesruleCoupon) {
		this.salesruleCoupon = salesruleCoupon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false, insertable = false, updatable = false)
	public CustomerEntity getCustomerEntity() {
		return this.customerEntity;
	}

	public void setCustomerEntity(CustomerEntity customerEntity) {
		this.customerEntity = customerEntity;
	}

	@Column(name = "times_used", nullable = false)
	public int getTimesUsed() {
		return this.timesUsed;
	}

	public void setTimesUsed(int timesUsed) {
		this.timesUsed = timesUsed;
	}

}
