package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SalesOrderTax generated by hbm2java
 */
@Entity
@Table(name = "sales_order_tax"
	, catalog = "magento")
public class SalesOrderTax implements java.io.Serializable {

	private Integer taxId;
	private int orderId;
	private String code;
	private String title;
	private BigDecimal percent;
	private BigDecimal amount;
	private int priority;
	private int position;
	private BigDecimal baseAmount;
	private short process;
	private BigDecimal baseRealAmount;
	private short hidden;
	private Set<SalesOrderTaxItem> salesOrderTaxItems = new HashSet<SalesOrderTaxItem>(0);

	public SalesOrderTax() {
	}

	public SalesOrderTax(int orderId, int priority, int position, short process, short hidden) {
		this.orderId = orderId;
		this.priority = priority;
		this.position = position;
		this.process = process;
		this.hidden = hidden;
	}

	public SalesOrderTax(int orderId, String code, String title, BigDecimal percent, BigDecimal amount, int priority, int position, BigDecimal baseAmount, short process, BigDecimal baseRealAmount, short hidden, Set<SalesOrderTaxItem> salesOrderTaxItems) {
		this.orderId = orderId;
		this.code = code;
		this.title = title;
		this.percent = percent;
		this.amount = amount;
		this.priority = priority;
		this.position = position;
		this.baseAmount = baseAmount;
		this.process = process;
		this.baseRealAmount = baseRealAmount;
		this.hidden = hidden;
		this.salesOrderTaxItems = salesOrderTaxItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tax_id", unique = true, nullable = false)
	public Integer getTaxId() {
		return this.taxId;
	}

	public void setTaxId(Integer taxId) {
		this.taxId = taxId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "percent", precision = 12, scale = 4)
	public BigDecimal getPercent() {
		return this.percent;
	}

	public void setPercent(BigDecimal percent) {
		this.percent = percent;
	}

	@Column(name = "amount", precision = 12, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "base_amount", precision = 12, scale = 4)
	public BigDecimal getBaseAmount() {
		return this.baseAmount;
	}

	public void setBaseAmount(BigDecimal baseAmount) {
		this.baseAmount = baseAmount;
	}

	@Column(name = "process", nullable = false)
	public short getProcess() {
		return this.process;
	}

	public void setProcess(short process) {
		this.process = process;
	}

	@Column(name = "base_real_amount", precision = 12, scale = 4)
	public BigDecimal getBaseRealAmount() {
		return this.baseRealAmount;
	}

	public void setBaseRealAmount(BigDecimal baseRealAmount) {
		this.baseRealAmount = baseRealAmount;
	}

	@Column(name = "hidden", nullable = false)
	public short getHidden() {
		return this.hidden;
	}

	public void setHidden(short hidden) {
		this.hidden = hidden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesOrderTax")
	public Set<SalesOrderTaxItem> getSalesOrderTaxItems() {
		return this.salesOrderTaxItems;
	}

	public void setSalesOrderTaxItems(Set<SalesOrderTaxItem> salesOrderTaxItems) {
		this.salesOrderTaxItems = salesOrderTaxItems;
	}

}
