package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.naver.mage4j.core.mage.core.model.resource.store.Store;

/**
 * SalesFlatOrder generated by hbm2java
 */
@Entity
@Table(name = "sales_flat_order"
	, catalog = "magento"
	, uniqueConstraints = @UniqueConstraint(columnNames = "increment_id"))
public class SalesFlatOrder implements java.io.Serializable {

	private Integer entityId;
	private CustomerEntity customerEntity;
	private Store coreStore;
	private String state;
	private String status;
	private String couponCode;
	private String protectCode;
	private String shippingDescription;
	private Short isVirtual;
	private BigDecimal baseDiscountAmount;
	private BigDecimal baseDiscountCanceled;
	private BigDecimal baseDiscountInvoiced;
	private BigDecimal baseDiscountRefunded;
	private BigDecimal baseGrandTotal;
	private BigDecimal baseShippingAmount;
	private BigDecimal baseShippingCanceled;
	private BigDecimal baseShippingInvoiced;
	private BigDecimal baseShippingRefunded;
	private BigDecimal baseShippingTaxAmount;
	private BigDecimal baseShippingTaxRefunded;
	private BigDecimal baseSubtotal;
	private BigDecimal baseSubtotalCanceled;
	private BigDecimal baseSubtotalInvoiced;
	private BigDecimal baseSubtotalRefunded;
	private BigDecimal baseTaxAmount;
	private BigDecimal baseTaxCanceled;
	private BigDecimal baseTaxInvoiced;
	private BigDecimal baseTaxRefunded;
	private BigDecimal baseToGlobalRate;
	private BigDecimal baseToOrderRate;
	private BigDecimal baseTotalCanceled;
	private BigDecimal baseTotalInvoiced;
	private BigDecimal baseTotalInvoicedCost;
	private BigDecimal baseTotalOfflineRefunded;
	private BigDecimal baseTotalOnlineRefunded;
	private BigDecimal baseTotalPaid;
	private BigDecimal baseTotalQtyOrdered;
	private BigDecimal baseTotalRefunded;
	private BigDecimal discountAmount;
	private BigDecimal discountCanceled;
	private BigDecimal discountInvoiced;
	private BigDecimal discountRefunded;
	private BigDecimal grandTotal;
	private BigDecimal shippingAmount;
	private BigDecimal shippingCanceled;
	private BigDecimal shippingInvoiced;
	private BigDecimal shippingRefunded;
	private BigDecimal shippingTaxAmount;
	private BigDecimal shippingTaxRefunded;
	private BigDecimal storeToBaseRate;
	private BigDecimal storeToOrderRate;
	private BigDecimal subtotal;
	private BigDecimal subtotalCanceled;
	private BigDecimal subtotalInvoiced;
	private BigDecimal subtotalRefunded;
	private BigDecimal taxAmount;
	private BigDecimal taxCanceled;
	private BigDecimal taxInvoiced;
	private BigDecimal taxRefunded;
	private BigDecimal totalCanceled;
	private BigDecimal totalInvoiced;
	private BigDecimal totalOfflineRefunded;
	private BigDecimal totalOnlineRefunded;
	private BigDecimal totalPaid;
	private BigDecimal totalQtyOrdered;
	private BigDecimal totalRefunded;
	private Short canShipPartially;
	private Short canShipPartiallyItem;
	private Short customerIsGuest;
	private Short customerNoteNotify;
	private Integer billingAddressId;
	private Short customerGroupId;
	private Integer editIncrement;
	private Short emailSent;
	private Short forcedShipmentWithInvoice;
	private Integer paymentAuthExpiration;
	private Integer quoteAddressId;
	private Integer quoteId;
	private Integer shippingAddressId;
	private BigDecimal adjustmentNegative;
	private BigDecimal adjustmentPositive;
	private BigDecimal baseAdjustmentNegative;
	private BigDecimal baseAdjustmentPositive;
	private BigDecimal baseShippingDiscountAmount;
	private BigDecimal baseSubtotalInclTax;
	private BigDecimal baseTotalDue;
	private BigDecimal paymentAuthorizationAmount;
	private BigDecimal shippingDiscountAmount;
	private BigDecimal subtotalInclTax;
	private BigDecimal totalDue;
	private BigDecimal weight;
	private Date customerDob;
	private String incrementId;
	private String appliedRuleIds;
	private String baseCurrencyCode;
	private String customerEmail;
	private String customerFirstname;
	private String customerLastname;
	private String customerMiddlename;
	private String customerPrefix;
	private String customerSuffix;
	private String customerTaxvat;
	private String discountDescription;
	private String extCustomerId;
	private String extOrderId;
	private String globalCurrencyCode;
	private String holdBeforeState;
	private String holdBeforeStatus;
	private String orderCurrencyCode;
	private String originalIncrementId;
	private String relationChildId;
	private String relationChildRealId;
	private String relationParentId;
	private String relationParentRealId;
	private String remoteIp;
	private String shippingMethod;
	private String storeCurrencyCode;
	private String storeName;
	private String XForwardedFor;
	private String customerNote;
	private Date createdAt;
	private Date updatedAt;
	private short totalItemCount;
	private Integer customerGender;
	private BigDecimal hiddenTaxAmount;
	private BigDecimal baseHiddenTaxAmount;
	private BigDecimal shippingHiddenTaxAmount;
	private BigDecimal baseShippingHiddenTaxAmnt;
	private BigDecimal hiddenTaxInvoiced;
	private BigDecimal baseHiddenTaxInvoiced;
	private BigDecimal hiddenTaxRefunded;
	private BigDecimal baseHiddenTaxRefunded;
	private BigDecimal shippingInclTax;
	private BigDecimal baseShippingInclTax;
	private String couponRuleName;
	private Integer paypalIpnCustomerNotified;
	private Integer giftMessageId;
	private Set<SalesFlatOrderItem> salesFlatOrderItems = new HashSet<SalesFlatOrderItem>(0);
	private Set<SalesPaymentTransaction> salesPaymentTransactions = new HashSet<SalesPaymentTransaction>(0);
	private SalesFlatOrderGrid salesFlatOrderGrid;
	private Set<SalesFlatOrderAddress> salesFlatOrderAddresses = new HashSet<SalesFlatOrderAddress>(0);
	private Set<SalesRecurringProfileOrder> salesRecurringProfileOrders = new HashSet<SalesRecurringProfileOrder>(0);
	private Set<SalesFlatShipment> salesFlatShipments = new HashSet<SalesFlatShipment>(0);
	private Set<DownloadableLinkPurchased> downloadableLinkPurchaseds = new HashSet<DownloadableLinkPurchased>(0);
	private Set<SalesFlatOrderPayment> salesFlatOrderPayments = new HashSet<SalesFlatOrderPayment>(0);
	private Set<SalesFlatInvoice> salesFlatInvoices = new HashSet<SalesFlatInvoice>(0);
	private Set<SalesFlatCreditmemo> salesFlatCreditmemos = new HashSet<SalesFlatCreditmemo>(0);
	private Set<SalesBillingAgreement> salesBillingAgreements = new HashSet<SalesBillingAgreement>(0);
	private Set<SalesFlatOrderStatusHistory> salesFlatOrderStatusHistories = new HashSet<SalesFlatOrderStatusHistory>(0);

	public SalesFlatOrder() {
	}

	public SalesFlatOrder(short totalItemCount) {
		this.totalItemCount = totalItemCount;
	}

	public SalesFlatOrder(CustomerEntity customerEntity, Store coreStore, String state, String status, String couponCode, String protectCode, String shippingDescription, Short isVirtual, BigDecimal baseDiscountAmount, BigDecimal baseDiscountCanceled, BigDecimal baseDiscountInvoiced, BigDecimal baseDiscountRefunded, BigDecimal baseGrandTotal, BigDecimal baseShippingAmount, BigDecimal baseShippingCanceled, BigDecimal baseShippingInvoiced, BigDecimal baseShippingRefunded,
		BigDecimal baseShippingTaxAmount, BigDecimal baseShippingTaxRefunded, BigDecimal baseSubtotal, BigDecimal baseSubtotalCanceled, BigDecimal baseSubtotalInvoiced, BigDecimal baseSubtotalRefunded, BigDecimal baseTaxAmount, BigDecimal baseTaxCanceled, BigDecimal baseTaxInvoiced, BigDecimal baseTaxRefunded, BigDecimal baseToGlobalRate, BigDecimal baseToOrderRate, BigDecimal baseTotalCanceled, BigDecimal baseTotalInvoiced, BigDecimal baseTotalInvoicedCost, BigDecimal baseTotalOfflineRefunded,
		BigDecimal baseTotalOnlineRefunded, BigDecimal baseTotalPaid, BigDecimal baseTotalQtyOrdered, BigDecimal baseTotalRefunded, BigDecimal discountAmount, BigDecimal discountCanceled, BigDecimal discountInvoiced, BigDecimal discountRefunded, BigDecimal grandTotal, BigDecimal shippingAmount, BigDecimal shippingCanceled, BigDecimal shippingInvoiced, BigDecimal shippingRefunded, BigDecimal shippingTaxAmount, BigDecimal shippingTaxRefunded, BigDecimal storeToBaseRate,
		BigDecimal storeToOrderRate, BigDecimal subtotal, BigDecimal subtotalCanceled, BigDecimal subtotalInvoiced, BigDecimal subtotalRefunded, BigDecimal taxAmount, BigDecimal taxCanceled, BigDecimal taxInvoiced, BigDecimal taxRefunded, BigDecimal totalCanceled, BigDecimal totalInvoiced, BigDecimal totalOfflineRefunded, BigDecimal totalOnlineRefunded, BigDecimal totalPaid, BigDecimal totalQtyOrdered, BigDecimal totalRefunded, Short canShipPartially, Short canShipPartiallyItem,
		Short customerIsGuest, Short customerNoteNotify, Integer billingAddressId, Short customerGroupId, Integer editIncrement, Short emailSent, Short forcedShipmentWithInvoice, Integer paymentAuthExpiration, Integer quoteAddressId, Integer quoteId, Integer shippingAddressId, BigDecimal adjustmentNegative, BigDecimal adjustmentPositive, BigDecimal baseAdjustmentNegative, BigDecimal baseAdjustmentPositive, BigDecimal baseShippingDiscountAmount, BigDecimal baseSubtotalInclTax,
		BigDecimal baseTotalDue, BigDecimal paymentAuthorizationAmount, BigDecimal shippingDiscountAmount, BigDecimal subtotalInclTax, BigDecimal totalDue, BigDecimal weight, Date customerDob, String incrementId, String appliedRuleIds, String baseCurrencyCode, String customerEmail, String customerFirstname, String customerLastname, String customerMiddlename, String customerPrefix, String customerSuffix, String customerTaxvat, String discountDescription, String extCustomerId, String extOrderId,
		String globalCurrencyCode, String holdBeforeState, String holdBeforeStatus, String orderCurrencyCode, String originalIncrementId, String relationChildId, String relationChildRealId, String relationParentId, String relationParentRealId, String remoteIp, String shippingMethod, String storeCurrencyCode, String storeName, String XForwardedFor, String customerNote, Date createdAt, Date updatedAt, short totalItemCount, Integer customerGender, BigDecimal hiddenTaxAmount,
		BigDecimal baseHiddenTaxAmount, BigDecimal shippingHiddenTaxAmount, BigDecimal baseShippingHiddenTaxAmnt, BigDecimal hiddenTaxInvoiced, BigDecimal baseHiddenTaxInvoiced, BigDecimal hiddenTaxRefunded, BigDecimal baseHiddenTaxRefunded, BigDecimal shippingInclTax, BigDecimal baseShippingInclTax, String couponRuleName, Integer paypalIpnCustomerNotified, Integer giftMessageId, Set<SalesFlatOrderItem> salesFlatOrderItems, Set<SalesPaymentTransaction> salesPaymentTransactions,
		SalesFlatOrderGrid salesFlatOrderGrid, Set<SalesFlatOrderAddress> salesFlatOrderAddresses, Set<SalesRecurringProfileOrder> salesRecurringProfileOrders, Set<SalesFlatShipment> salesFlatShipments, Set<DownloadableLinkPurchased> downloadableLinkPurchaseds, Set<SalesFlatOrderPayment> salesFlatOrderPayments, Set<SalesFlatInvoice> salesFlatInvoices, Set<SalesFlatCreditmemo> salesFlatCreditmemos, Set<SalesBillingAgreement> salesBillingAgreements,
		Set<SalesFlatOrderStatusHistory> salesFlatOrderStatusHistories) {
		this.customerEntity = customerEntity;
		this.coreStore = coreStore;
		this.state = state;
		this.status = status;
		this.couponCode = couponCode;
		this.protectCode = protectCode;
		this.shippingDescription = shippingDescription;
		this.isVirtual = isVirtual;
		this.baseDiscountAmount = baseDiscountAmount;
		this.baseDiscountCanceled = baseDiscountCanceled;
		this.baseDiscountInvoiced = baseDiscountInvoiced;
		this.baseDiscountRefunded = baseDiscountRefunded;
		this.baseGrandTotal = baseGrandTotal;
		this.baseShippingAmount = baseShippingAmount;
		this.baseShippingCanceled = baseShippingCanceled;
		this.baseShippingInvoiced = baseShippingInvoiced;
		this.baseShippingRefunded = baseShippingRefunded;
		this.baseShippingTaxAmount = baseShippingTaxAmount;
		this.baseShippingTaxRefunded = baseShippingTaxRefunded;
		this.baseSubtotal = baseSubtotal;
		this.baseSubtotalCanceled = baseSubtotalCanceled;
		this.baseSubtotalInvoiced = baseSubtotalInvoiced;
		this.baseSubtotalRefunded = baseSubtotalRefunded;
		this.baseTaxAmount = baseTaxAmount;
		this.baseTaxCanceled = baseTaxCanceled;
		this.baseTaxInvoiced = baseTaxInvoiced;
		this.baseTaxRefunded = baseTaxRefunded;
		this.baseToGlobalRate = baseToGlobalRate;
		this.baseToOrderRate = baseToOrderRate;
		this.baseTotalCanceled = baseTotalCanceled;
		this.baseTotalInvoiced = baseTotalInvoiced;
		this.baseTotalInvoicedCost = baseTotalInvoicedCost;
		this.baseTotalOfflineRefunded = baseTotalOfflineRefunded;
		this.baseTotalOnlineRefunded = baseTotalOnlineRefunded;
		this.baseTotalPaid = baseTotalPaid;
		this.baseTotalQtyOrdered = baseTotalQtyOrdered;
		this.baseTotalRefunded = baseTotalRefunded;
		this.discountAmount = discountAmount;
		this.discountCanceled = discountCanceled;
		this.discountInvoiced = discountInvoiced;
		this.discountRefunded = discountRefunded;
		this.grandTotal = grandTotal;
		this.shippingAmount = shippingAmount;
		this.shippingCanceled = shippingCanceled;
		this.shippingInvoiced = shippingInvoiced;
		this.shippingRefunded = shippingRefunded;
		this.shippingTaxAmount = shippingTaxAmount;
		this.shippingTaxRefunded = shippingTaxRefunded;
		this.storeToBaseRate = storeToBaseRate;
		this.storeToOrderRate = storeToOrderRate;
		this.subtotal = subtotal;
		this.subtotalCanceled = subtotalCanceled;
		this.subtotalInvoiced = subtotalInvoiced;
		this.subtotalRefunded = subtotalRefunded;
		this.taxAmount = taxAmount;
		this.taxCanceled = taxCanceled;
		this.taxInvoiced = taxInvoiced;
		this.taxRefunded = taxRefunded;
		this.totalCanceled = totalCanceled;
		this.totalInvoiced = totalInvoiced;
		this.totalOfflineRefunded = totalOfflineRefunded;
		this.totalOnlineRefunded = totalOnlineRefunded;
		this.totalPaid = totalPaid;
		this.totalQtyOrdered = totalQtyOrdered;
		this.totalRefunded = totalRefunded;
		this.canShipPartially = canShipPartially;
		this.canShipPartiallyItem = canShipPartiallyItem;
		this.customerIsGuest = customerIsGuest;
		this.customerNoteNotify = customerNoteNotify;
		this.billingAddressId = billingAddressId;
		this.customerGroupId = customerGroupId;
		this.editIncrement = editIncrement;
		this.emailSent = emailSent;
		this.forcedShipmentWithInvoice = forcedShipmentWithInvoice;
		this.paymentAuthExpiration = paymentAuthExpiration;
		this.quoteAddressId = quoteAddressId;
		this.quoteId = quoteId;
		this.shippingAddressId = shippingAddressId;
		this.adjustmentNegative = adjustmentNegative;
		this.adjustmentPositive = adjustmentPositive;
		this.baseAdjustmentNegative = baseAdjustmentNegative;
		this.baseAdjustmentPositive = baseAdjustmentPositive;
		this.baseShippingDiscountAmount = baseShippingDiscountAmount;
		this.baseSubtotalInclTax = baseSubtotalInclTax;
		this.baseTotalDue = baseTotalDue;
		this.paymentAuthorizationAmount = paymentAuthorizationAmount;
		this.shippingDiscountAmount = shippingDiscountAmount;
		this.subtotalInclTax = subtotalInclTax;
		this.totalDue = totalDue;
		this.weight = weight;
		this.customerDob = customerDob;
		this.incrementId = incrementId;
		this.appliedRuleIds = appliedRuleIds;
		this.baseCurrencyCode = baseCurrencyCode;
		this.customerEmail = customerEmail;
		this.customerFirstname = customerFirstname;
		this.customerLastname = customerLastname;
		this.customerMiddlename = customerMiddlename;
		this.customerPrefix = customerPrefix;
		this.customerSuffix = customerSuffix;
		this.customerTaxvat = customerTaxvat;
		this.discountDescription = discountDescription;
		this.extCustomerId = extCustomerId;
		this.extOrderId = extOrderId;
		this.globalCurrencyCode = globalCurrencyCode;
		this.holdBeforeState = holdBeforeState;
		this.holdBeforeStatus = holdBeforeStatus;
		this.orderCurrencyCode = orderCurrencyCode;
		this.originalIncrementId = originalIncrementId;
		this.relationChildId = relationChildId;
		this.relationChildRealId = relationChildRealId;
		this.relationParentId = relationParentId;
		this.relationParentRealId = relationParentRealId;
		this.remoteIp = remoteIp;
		this.shippingMethod = shippingMethod;
		this.storeCurrencyCode = storeCurrencyCode;
		this.storeName = storeName;
		this.XForwardedFor = XForwardedFor;
		this.customerNote = customerNote;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.totalItemCount = totalItemCount;
		this.customerGender = customerGender;
		this.hiddenTaxAmount = hiddenTaxAmount;
		this.baseHiddenTaxAmount = baseHiddenTaxAmount;
		this.shippingHiddenTaxAmount = shippingHiddenTaxAmount;
		this.baseShippingHiddenTaxAmnt = baseShippingHiddenTaxAmnt;
		this.hiddenTaxInvoiced = hiddenTaxInvoiced;
		this.baseHiddenTaxInvoiced = baseHiddenTaxInvoiced;
		this.hiddenTaxRefunded = hiddenTaxRefunded;
		this.baseHiddenTaxRefunded = baseHiddenTaxRefunded;
		this.shippingInclTax = shippingInclTax;
		this.baseShippingInclTax = baseShippingInclTax;
		this.couponRuleName = couponRuleName;
		this.paypalIpnCustomerNotified = paypalIpnCustomerNotified;
		this.giftMessageId = giftMessageId;
		this.salesFlatOrderItems = salesFlatOrderItems;
		this.salesPaymentTransactions = salesPaymentTransactions;
		this.salesFlatOrderGrid = salesFlatOrderGrid;
		this.salesFlatOrderAddresses = salesFlatOrderAddresses;
		this.salesRecurringProfileOrders = salesRecurringProfileOrders;
		this.salesFlatShipments = salesFlatShipments;
		this.downloadableLinkPurchaseds = downloadableLinkPurchaseds;
		this.salesFlatOrderPayments = salesFlatOrderPayments;
		this.salesFlatInvoices = salesFlatInvoices;
		this.salesFlatCreditmemos = salesFlatCreditmemos;
		this.salesBillingAgreements = salesBillingAgreements;
		this.salesFlatOrderStatusHistories = salesFlatOrderStatusHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public CustomerEntity getCustomerEntity() {
		return this.customerEntity;
	}

	public void setCustomerEntity(CustomerEntity customerEntity) {
		this.customerEntity = customerEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getCoreStore() {
		return this.coreStore;
	}

	public void setCoreStore(Store coreStore) {
		this.coreStore = coreStore;
	}

	@Column(name = "state", length = 32)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "status", length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "coupon_code")
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@Column(name = "protect_code")
	public String getProtectCode() {
		return this.protectCode;
	}

	public void setProtectCode(String protectCode) {
		this.protectCode = protectCode;
	}

	@Column(name = "shipping_description")
	public String getShippingDescription() {
		return this.shippingDescription;
	}

	public void setShippingDescription(String shippingDescription) {
		this.shippingDescription = shippingDescription;
	}

	@Column(name = "is_virtual")
	public Short getIsVirtual() {
		return this.isVirtual;
	}

	public void setIsVirtual(Short isVirtual) {
		this.isVirtual = isVirtual;
	}

	@Column(name = "base_discount_amount", precision = 12, scale = 4)
	public BigDecimal getBaseDiscountAmount() {
		return this.baseDiscountAmount;
	}

	public void setBaseDiscountAmount(BigDecimal baseDiscountAmount) {
		this.baseDiscountAmount = baseDiscountAmount;
	}

	@Column(name = "base_discount_canceled", precision = 12, scale = 4)
	public BigDecimal getBaseDiscountCanceled() {
		return this.baseDiscountCanceled;
	}

	public void setBaseDiscountCanceled(BigDecimal baseDiscountCanceled) {
		this.baseDiscountCanceled = baseDiscountCanceled;
	}

	@Column(name = "base_discount_invoiced", precision = 12, scale = 4)
	public BigDecimal getBaseDiscountInvoiced() {
		return this.baseDiscountInvoiced;
	}

	public void setBaseDiscountInvoiced(BigDecimal baseDiscountInvoiced) {
		this.baseDiscountInvoiced = baseDiscountInvoiced;
	}

	@Column(name = "base_discount_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseDiscountRefunded() {
		return this.baseDiscountRefunded;
	}

	public void setBaseDiscountRefunded(BigDecimal baseDiscountRefunded) {
		this.baseDiscountRefunded = baseDiscountRefunded;
	}

	@Column(name = "base_grand_total", precision = 12, scale = 4)
	public BigDecimal getBaseGrandTotal() {
		return this.baseGrandTotal;
	}

	public void setBaseGrandTotal(BigDecimal baseGrandTotal) {
		this.baseGrandTotal = baseGrandTotal;
	}

	@Column(name = "base_shipping_amount", precision = 12, scale = 4)
	public BigDecimal getBaseShippingAmount() {
		return this.baseShippingAmount;
	}

	public void setBaseShippingAmount(BigDecimal baseShippingAmount) {
		this.baseShippingAmount = baseShippingAmount;
	}

	@Column(name = "base_shipping_canceled", precision = 12, scale = 4)
	public BigDecimal getBaseShippingCanceled() {
		return this.baseShippingCanceled;
	}

	public void setBaseShippingCanceled(BigDecimal baseShippingCanceled) {
		this.baseShippingCanceled = baseShippingCanceled;
	}

	@Column(name = "base_shipping_invoiced", precision = 12, scale = 4)
	public BigDecimal getBaseShippingInvoiced() {
		return this.baseShippingInvoiced;
	}

	public void setBaseShippingInvoiced(BigDecimal baseShippingInvoiced) {
		this.baseShippingInvoiced = baseShippingInvoiced;
	}

	@Column(name = "base_shipping_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseShippingRefunded() {
		return this.baseShippingRefunded;
	}

	public void setBaseShippingRefunded(BigDecimal baseShippingRefunded) {
		this.baseShippingRefunded = baseShippingRefunded;
	}

	@Column(name = "base_shipping_tax_amount", precision = 12, scale = 4)
	public BigDecimal getBaseShippingTaxAmount() {
		return this.baseShippingTaxAmount;
	}

	public void setBaseShippingTaxAmount(BigDecimal baseShippingTaxAmount) {
		this.baseShippingTaxAmount = baseShippingTaxAmount;
	}

	@Column(name = "base_shipping_tax_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseShippingTaxRefunded() {
		return this.baseShippingTaxRefunded;
	}

	public void setBaseShippingTaxRefunded(BigDecimal baseShippingTaxRefunded) {
		this.baseShippingTaxRefunded = baseShippingTaxRefunded;
	}

	@Column(name = "base_subtotal", precision = 12, scale = 4)
	public BigDecimal getBaseSubtotal() {
		return this.baseSubtotal;
	}

	public void setBaseSubtotal(BigDecimal baseSubtotal) {
		this.baseSubtotal = baseSubtotal;
	}

	@Column(name = "base_subtotal_canceled", precision = 12, scale = 4)
	public BigDecimal getBaseSubtotalCanceled() {
		return this.baseSubtotalCanceled;
	}

	public void setBaseSubtotalCanceled(BigDecimal baseSubtotalCanceled) {
		this.baseSubtotalCanceled = baseSubtotalCanceled;
	}

	@Column(name = "base_subtotal_invoiced", precision = 12, scale = 4)
	public BigDecimal getBaseSubtotalInvoiced() {
		return this.baseSubtotalInvoiced;
	}

	public void setBaseSubtotalInvoiced(BigDecimal baseSubtotalInvoiced) {
		this.baseSubtotalInvoiced = baseSubtotalInvoiced;
	}

	@Column(name = "base_subtotal_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseSubtotalRefunded() {
		return this.baseSubtotalRefunded;
	}

	public void setBaseSubtotalRefunded(BigDecimal baseSubtotalRefunded) {
		this.baseSubtotalRefunded = baseSubtotalRefunded;
	}

	@Column(name = "base_tax_amount", precision = 12, scale = 4)
	public BigDecimal getBaseTaxAmount() {
		return this.baseTaxAmount;
	}

	public void setBaseTaxAmount(BigDecimal baseTaxAmount) {
		this.baseTaxAmount = baseTaxAmount;
	}

	@Column(name = "base_tax_canceled", precision = 12, scale = 4)
	public BigDecimal getBaseTaxCanceled() {
		return this.baseTaxCanceled;
	}

	public void setBaseTaxCanceled(BigDecimal baseTaxCanceled) {
		this.baseTaxCanceled = baseTaxCanceled;
	}

	@Column(name = "base_tax_invoiced", precision = 12, scale = 4)
	public BigDecimal getBaseTaxInvoiced() {
		return this.baseTaxInvoiced;
	}

	public void setBaseTaxInvoiced(BigDecimal baseTaxInvoiced) {
		this.baseTaxInvoiced = baseTaxInvoiced;
	}

	@Column(name = "base_tax_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseTaxRefunded() {
		return this.baseTaxRefunded;
	}

	public void setBaseTaxRefunded(BigDecimal baseTaxRefunded) {
		this.baseTaxRefunded = baseTaxRefunded;
	}

	@Column(name = "base_to_global_rate", precision = 12, scale = 4)
	public BigDecimal getBaseToGlobalRate() {
		return this.baseToGlobalRate;
	}

	public void setBaseToGlobalRate(BigDecimal baseToGlobalRate) {
		this.baseToGlobalRate = baseToGlobalRate;
	}

	@Column(name = "base_to_order_rate", precision = 12, scale = 4)
	public BigDecimal getBaseToOrderRate() {
		return this.baseToOrderRate;
	}

	public void setBaseToOrderRate(BigDecimal baseToOrderRate) {
		this.baseToOrderRate = baseToOrderRate;
	}

	@Column(name = "base_total_canceled", precision = 12, scale = 4)
	public BigDecimal getBaseTotalCanceled() {
		return this.baseTotalCanceled;
	}

	public void setBaseTotalCanceled(BigDecimal baseTotalCanceled) {
		this.baseTotalCanceled = baseTotalCanceled;
	}

	@Column(name = "base_total_invoiced", precision = 12, scale = 4)
	public BigDecimal getBaseTotalInvoiced() {
		return this.baseTotalInvoiced;
	}

	public void setBaseTotalInvoiced(BigDecimal baseTotalInvoiced) {
		this.baseTotalInvoiced = baseTotalInvoiced;
	}

	@Column(name = "base_total_invoiced_cost", precision = 12, scale = 4)
	public BigDecimal getBaseTotalInvoicedCost() {
		return this.baseTotalInvoicedCost;
	}

	public void setBaseTotalInvoicedCost(BigDecimal baseTotalInvoicedCost) {
		this.baseTotalInvoicedCost = baseTotalInvoicedCost;
	}

	@Column(name = "base_total_offline_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseTotalOfflineRefunded() {
		return this.baseTotalOfflineRefunded;
	}

	public void setBaseTotalOfflineRefunded(BigDecimal baseTotalOfflineRefunded) {
		this.baseTotalOfflineRefunded = baseTotalOfflineRefunded;
	}

	@Column(name = "base_total_online_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseTotalOnlineRefunded() {
		return this.baseTotalOnlineRefunded;
	}

	public void setBaseTotalOnlineRefunded(BigDecimal baseTotalOnlineRefunded) {
		this.baseTotalOnlineRefunded = baseTotalOnlineRefunded;
	}

	@Column(name = "base_total_paid", precision = 12, scale = 4)
	public BigDecimal getBaseTotalPaid() {
		return this.baseTotalPaid;
	}

	public void setBaseTotalPaid(BigDecimal baseTotalPaid) {
		this.baseTotalPaid = baseTotalPaid;
	}

	@Column(name = "base_total_qty_ordered", precision = 12, scale = 4)
	public BigDecimal getBaseTotalQtyOrdered() {
		return this.baseTotalQtyOrdered;
	}

	public void setBaseTotalQtyOrdered(BigDecimal baseTotalQtyOrdered) {
		this.baseTotalQtyOrdered = baseTotalQtyOrdered;
	}

	@Column(name = "base_total_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseTotalRefunded() {
		return this.baseTotalRefunded;
	}

	public void setBaseTotalRefunded(BigDecimal baseTotalRefunded) {
		this.baseTotalRefunded = baseTotalRefunded;
	}

	@Column(name = "discount_amount", precision = 12, scale = 4)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "discount_canceled", precision = 12, scale = 4)
	public BigDecimal getDiscountCanceled() {
		return this.discountCanceled;
	}

	public void setDiscountCanceled(BigDecimal discountCanceled) {
		this.discountCanceled = discountCanceled;
	}

	@Column(name = "discount_invoiced", precision = 12, scale = 4)
	public BigDecimal getDiscountInvoiced() {
		return this.discountInvoiced;
	}

	public void setDiscountInvoiced(BigDecimal discountInvoiced) {
		this.discountInvoiced = discountInvoiced;
	}

	@Column(name = "discount_refunded", precision = 12, scale = 4)
	public BigDecimal getDiscountRefunded() {
		return this.discountRefunded;
	}

	public void setDiscountRefunded(BigDecimal discountRefunded) {
		this.discountRefunded = discountRefunded;
	}

	@Column(name = "grand_total", precision = 12, scale = 4)
	public BigDecimal getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(BigDecimal grandTotal) {
		this.grandTotal = grandTotal;
	}

	@Column(name = "shipping_amount", precision = 12, scale = 4)
	public BigDecimal getShippingAmount() {
		return this.shippingAmount;
	}

	public void setShippingAmount(BigDecimal shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	@Column(name = "shipping_canceled", precision = 12, scale = 4)
	public BigDecimal getShippingCanceled() {
		return this.shippingCanceled;
	}

	public void setShippingCanceled(BigDecimal shippingCanceled) {
		this.shippingCanceled = shippingCanceled;
	}

	@Column(name = "shipping_invoiced", precision = 12, scale = 4)
	public BigDecimal getShippingInvoiced() {
		return this.shippingInvoiced;
	}

	public void setShippingInvoiced(BigDecimal shippingInvoiced) {
		this.shippingInvoiced = shippingInvoiced;
	}

	@Column(name = "shipping_refunded", precision = 12, scale = 4)
	public BigDecimal getShippingRefunded() {
		return this.shippingRefunded;
	}

	public void setShippingRefunded(BigDecimal shippingRefunded) {
		this.shippingRefunded = shippingRefunded;
	}

	@Column(name = "shipping_tax_amount", precision = 12, scale = 4)
	public BigDecimal getShippingTaxAmount() {
		return this.shippingTaxAmount;
	}

	public void setShippingTaxAmount(BigDecimal shippingTaxAmount) {
		this.shippingTaxAmount = shippingTaxAmount;
	}

	@Column(name = "shipping_tax_refunded", precision = 12, scale = 4)
	public BigDecimal getShippingTaxRefunded() {
		return this.shippingTaxRefunded;
	}

	public void setShippingTaxRefunded(BigDecimal shippingTaxRefunded) {
		this.shippingTaxRefunded = shippingTaxRefunded;
	}

	@Column(name = "store_to_base_rate", precision = 12, scale = 4)
	public BigDecimal getStoreToBaseRate() {
		return this.storeToBaseRate;
	}

	public void setStoreToBaseRate(BigDecimal storeToBaseRate) {
		this.storeToBaseRate = storeToBaseRate;
	}

	@Column(name = "store_to_order_rate", precision = 12, scale = 4)
	public BigDecimal getStoreToOrderRate() {
		return this.storeToOrderRate;
	}

	public void setStoreToOrderRate(BigDecimal storeToOrderRate) {
		this.storeToOrderRate = storeToOrderRate;
	}

	@Column(name = "subtotal", precision = 12, scale = 4)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "subtotal_canceled", precision = 12, scale = 4)
	public BigDecimal getSubtotalCanceled() {
		return this.subtotalCanceled;
	}

	public void setSubtotalCanceled(BigDecimal subtotalCanceled) {
		this.subtotalCanceled = subtotalCanceled;
	}

	@Column(name = "subtotal_invoiced", precision = 12, scale = 4)
	public BigDecimal getSubtotalInvoiced() {
		return this.subtotalInvoiced;
	}

	public void setSubtotalInvoiced(BigDecimal subtotalInvoiced) {
		this.subtotalInvoiced = subtotalInvoiced;
	}

	@Column(name = "subtotal_refunded", precision = 12, scale = 4)
	public BigDecimal getSubtotalRefunded() {
		return this.subtotalRefunded;
	}

	public void setSubtotalRefunded(BigDecimal subtotalRefunded) {
		this.subtotalRefunded = subtotalRefunded;
	}

	@Column(name = "tax_amount", precision = 12, scale = 4)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "tax_canceled", precision = 12, scale = 4)
	public BigDecimal getTaxCanceled() {
		return this.taxCanceled;
	}

	public void setTaxCanceled(BigDecimal taxCanceled) {
		this.taxCanceled = taxCanceled;
	}

	@Column(name = "tax_invoiced", precision = 12, scale = 4)
	public BigDecimal getTaxInvoiced() {
		return this.taxInvoiced;
	}

	public void setTaxInvoiced(BigDecimal taxInvoiced) {
		this.taxInvoiced = taxInvoiced;
	}

	@Column(name = "tax_refunded", precision = 12, scale = 4)
	public BigDecimal getTaxRefunded() {
		return this.taxRefunded;
	}

	public void setTaxRefunded(BigDecimal taxRefunded) {
		this.taxRefunded = taxRefunded;
	}

	@Column(name = "total_canceled", precision = 12, scale = 4)
	public BigDecimal getTotalCanceled() {
		return this.totalCanceled;
	}

	public void setTotalCanceled(BigDecimal totalCanceled) {
		this.totalCanceled = totalCanceled;
	}

	@Column(name = "total_invoiced", precision = 12, scale = 4)
	public BigDecimal getTotalInvoiced() {
		return this.totalInvoiced;
	}

	public void setTotalInvoiced(BigDecimal totalInvoiced) {
		this.totalInvoiced = totalInvoiced;
	}

	@Column(name = "total_offline_refunded", precision = 12, scale = 4)
	public BigDecimal getTotalOfflineRefunded() {
		return this.totalOfflineRefunded;
	}

	public void setTotalOfflineRefunded(BigDecimal totalOfflineRefunded) {
		this.totalOfflineRefunded = totalOfflineRefunded;
	}

	@Column(name = "total_online_refunded", precision = 12, scale = 4)
	public BigDecimal getTotalOnlineRefunded() {
		return this.totalOnlineRefunded;
	}

	public void setTotalOnlineRefunded(BigDecimal totalOnlineRefunded) {
		this.totalOnlineRefunded = totalOnlineRefunded;
	}

	@Column(name = "total_paid", precision = 12, scale = 4)
	public BigDecimal getTotalPaid() {
		return this.totalPaid;
	}

	public void setTotalPaid(BigDecimal totalPaid) {
		this.totalPaid = totalPaid;
	}

	@Column(name = "total_qty_ordered", precision = 12, scale = 4)
	public BigDecimal getTotalQtyOrdered() {
		return this.totalQtyOrdered;
	}

	public void setTotalQtyOrdered(BigDecimal totalQtyOrdered) {
		this.totalQtyOrdered = totalQtyOrdered;
	}

	@Column(name = "total_refunded", precision = 12, scale = 4)
	public BigDecimal getTotalRefunded() {
		return this.totalRefunded;
	}

	public void setTotalRefunded(BigDecimal totalRefunded) {
		this.totalRefunded = totalRefunded;
	}

	@Column(name = "can_ship_partially")
	public Short getCanShipPartially() {
		return this.canShipPartially;
	}

	public void setCanShipPartially(Short canShipPartially) {
		this.canShipPartially = canShipPartially;
	}

	@Column(name = "can_ship_partially_item")
	public Short getCanShipPartiallyItem() {
		return this.canShipPartiallyItem;
	}

	public void setCanShipPartiallyItem(Short canShipPartiallyItem) {
		this.canShipPartiallyItem = canShipPartiallyItem;
	}

	@Column(name = "customer_is_guest")
	public Short getCustomerIsGuest() {
		return this.customerIsGuest;
	}

	public void setCustomerIsGuest(Short customerIsGuest) {
		this.customerIsGuest = customerIsGuest;
	}

	@Column(name = "customer_note_notify")
	public Short getCustomerNoteNotify() {
		return this.customerNoteNotify;
	}

	public void setCustomerNoteNotify(Short customerNoteNotify) {
		this.customerNoteNotify = customerNoteNotify;
	}

	@Column(name = "billing_address_id")
	public Integer getBillingAddressId() {
		return this.billingAddressId;
	}

	public void setBillingAddressId(Integer billingAddressId) {
		this.billingAddressId = billingAddressId;
	}

	@Column(name = "customer_group_id")
	public Short getCustomerGroupId() {
		return this.customerGroupId;
	}

	public void setCustomerGroupId(Short customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

	@Column(name = "edit_increment")
	public Integer getEditIncrement() {
		return this.editIncrement;
	}

	public void setEditIncrement(Integer editIncrement) {
		this.editIncrement = editIncrement;
	}

	@Column(name = "email_sent")
	public Short getEmailSent() {
		return this.emailSent;
	}

	public void setEmailSent(Short emailSent) {
		this.emailSent = emailSent;
	}

	@Column(name = "forced_shipment_with_invoice")
	public Short getForcedShipmentWithInvoice() {
		return this.forcedShipmentWithInvoice;
	}

	public void setForcedShipmentWithInvoice(Short forcedShipmentWithInvoice) {
		this.forcedShipmentWithInvoice = forcedShipmentWithInvoice;
	}

	@Column(name = "payment_auth_expiration")
	public Integer getPaymentAuthExpiration() {
		return this.paymentAuthExpiration;
	}

	public void setPaymentAuthExpiration(Integer paymentAuthExpiration) {
		this.paymentAuthExpiration = paymentAuthExpiration;
	}

	@Column(name = "quote_address_id")
	public Integer getQuoteAddressId() {
		return this.quoteAddressId;
	}

	public void setQuoteAddressId(Integer quoteAddressId) {
		this.quoteAddressId = quoteAddressId;
	}

	@Column(name = "quote_id")
	public Integer getQuoteId() {
		return this.quoteId;
	}

	public void setQuoteId(Integer quoteId) {
		this.quoteId = quoteId;
	}

	@Column(name = "shipping_address_id")
	public Integer getShippingAddressId() {
		return this.shippingAddressId;
	}

	public void setShippingAddressId(Integer shippingAddressId) {
		this.shippingAddressId = shippingAddressId;
	}

	@Column(name = "adjustment_negative", precision = 12, scale = 4)
	public BigDecimal getAdjustmentNegative() {
		return this.adjustmentNegative;
	}

	public void setAdjustmentNegative(BigDecimal adjustmentNegative) {
		this.adjustmentNegative = adjustmentNegative;
	}

	@Column(name = "adjustment_positive", precision = 12, scale = 4)
	public BigDecimal getAdjustmentPositive() {
		return this.adjustmentPositive;
	}

	public void setAdjustmentPositive(BigDecimal adjustmentPositive) {
		this.adjustmentPositive = adjustmentPositive;
	}

	@Column(name = "base_adjustment_negative", precision = 12, scale = 4)
	public BigDecimal getBaseAdjustmentNegative() {
		return this.baseAdjustmentNegative;
	}

	public void setBaseAdjustmentNegative(BigDecimal baseAdjustmentNegative) {
		this.baseAdjustmentNegative = baseAdjustmentNegative;
	}

	@Column(name = "base_adjustment_positive", precision = 12, scale = 4)
	public BigDecimal getBaseAdjustmentPositive() {
		return this.baseAdjustmentPositive;
	}

	public void setBaseAdjustmentPositive(BigDecimal baseAdjustmentPositive) {
		this.baseAdjustmentPositive = baseAdjustmentPositive;
	}

	@Column(name = "base_shipping_discount_amount", precision = 12, scale = 4)
	public BigDecimal getBaseShippingDiscountAmount() {
		return this.baseShippingDiscountAmount;
	}

	public void setBaseShippingDiscountAmount(BigDecimal baseShippingDiscountAmount) {
		this.baseShippingDiscountAmount = baseShippingDiscountAmount;
	}

	@Column(name = "base_subtotal_incl_tax", precision = 12, scale = 4)
	public BigDecimal getBaseSubtotalInclTax() {
		return this.baseSubtotalInclTax;
	}

	public void setBaseSubtotalInclTax(BigDecimal baseSubtotalInclTax) {
		this.baseSubtotalInclTax = baseSubtotalInclTax;
	}

	@Column(name = "base_total_due", precision = 12, scale = 4)
	public BigDecimal getBaseTotalDue() {
		return this.baseTotalDue;
	}

	public void setBaseTotalDue(BigDecimal baseTotalDue) {
		this.baseTotalDue = baseTotalDue;
	}

	@Column(name = "payment_authorization_amount", precision = 12, scale = 4)
	public BigDecimal getPaymentAuthorizationAmount() {
		return this.paymentAuthorizationAmount;
	}

	public void setPaymentAuthorizationAmount(BigDecimal paymentAuthorizationAmount) {
		this.paymentAuthorizationAmount = paymentAuthorizationAmount;
	}

	@Column(name = "shipping_discount_amount", precision = 12, scale = 4)
	public BigDecimal getShippingDiscountAmount() {
		return this.shippingDiscountAmount;
	}

	public void setShippingDiscountAmount(BigDecimal shippingDiscountAmount) {
		this.shippingDiscountAmount = shippingDiscountAmount;
	}

	@Column(name = "subtotal_incl_tax", precision = 12, scale = 4)
	public BigDecimal getSubtotalInclTax() {
		return this.subtotalInclTax;
	}

	public void setSubtotalInclTax(BigDecimal subtotalInclTax) {
		this.subtotalInclTax = subtotalInclTax;
	}

	@Column(name = "total_due", precision = 12, scale = 4)
	public BigDecimal getTotalDue() {
		return this.totalDue;
	}

	public void setTotalDue(BigDecimal totalDue) {
		this.totalDue = totalDue;
	}

	@Column(name = "weight", precision = 12, scale = 4)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "customer_dob", length = 19)
	public Date getCustomerDob() {
		return this.customerDob;
	}

	public void setCustomerDob(Date customerDob) {
		this.customerDob = customerDob;
	}

	@Column(name = "increment_id", unique = true, length = 50)
	public String getIncrementId() {
		return this.incrementId;
	}

	public void setIncrementId(String incrementId) {
		this.incrementId = incrementId;
	}

	@Column(name = "applied_rule_ids")
	public String getAppliedRuleIds() {
		return this.appliedRuleIds;
	}

	public void setAppliedRuleIds(String appliedRuleIds) {
		this.appliedRuleIds = appliedRuleIds;
	}

	@Column(name = "base_currency_code", length = 3)
	public String getBaseCurrencyCode() {
		return this.baseCurrencyCode;
	}

	public void setBaseCurrencyCode(String baseCurrencyCode) {
		this.baseCurrencyCode = baseCurrencyCode;
	}

	@Column(name = "customer_email")
	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	@Column(name = "customer_firstname")
	public String getCustomerFirstname() {
		return this.customerFirstname;
	}

	public void setCustomerFirstname(String customerFirstname) {
		this.customerFirstname = customerFirstname;
	}

	@Column(name = "customer_lastname")
	public String getCustomerLastname() {
		return this.customerLastname;
	}

	public void setCustomerLastname(String customerLastname) {
		this.customerLastname = customerLastname;
	}

	@Column(name = "customer_middlename")
	public String getCustomerMiddlename() {
		return this.customerMiddlename;
	}

	public void setCustomerMiddlename(String customerMiddlename) {
		this.customerMiddlename = customerMiddlename;
	}

	@Column(name = "customer_prefix")
	public String getCustomerPrefix() {
		return this.customerPrefix;
	}

	public void setCustomerPrefix(String customerPrefix) {
		this.customerPrefix = customerPrefix;
	}

	@Column(name = "customer_suffix")
	public String getCustomerSuffix() {
		return this.customerSuffix;
	}

	public void setCustomerSuffix(String customerSuffix) {
		this.customerSuffix = customerSuffix;
	}

	@Column(name = "customer_taxvat")
	public String getCustomerTaxvat() {
		return this.customerTaxvat;
	}

	public void setCustomerTaxvat(String customerTaxvat) {
		this.customerTaxvat = customerTaxvat;
	}

	@Column(name = "discount_description")
	public String getDiscountDescription() {
		return this.discountDescription;
	}

	public void setDiscountDescription(String discountDescription) {
		this.discountDescription = discountDescription;
	}

	@Column(name = "ext_customer_id")
	public String getExtCustomerId() {
		return this.extCustomerId;
	}

	public void setExtCustomerId(String extCustomerId) {
		this.extCustomerId = extCustomerId;
	}

	@Column(name = "ext_order_id")
	public String getExtOrderId() {
		return this.extOrderId;
	}

	public void setExtOrderId(String extOrderId) {
		this.extOrderId = extOrderId;
	}

	@Column(name = "global_currency_code", length = 3)
	public String getGlobalCurrencyCode() {
		return this.globalCurrencyCode;
	}

	public void setGlobalCurrencyCode(String globalCurrencyCode) {
		this.globalCurrencyCode = globalCurrencyCode;
	}

	@Column(name = "hold_before_state")
	public String getHoldBeforeState() {
		return this.holdBeforeState;
	}

	public void setHoldBeforeState(String holdBeforeState) {
		this.holdBeforeState = holdBeforeState;
	}

	@Column(name = "hold_before_status")
	public String getHoldBeforeStatus() {
		return this.holdBeforeStatus;
	}

	public void setHoldBeforeStatus(String holdBeforeStatus) {
		this.holdBeforeStatus = holdBeforeStatus;
	}

	@Column(name = "order_currency_code")
	public String getOrderCurrencyCode() {
		return this.orderCurrencyCode;
	}

	public void setOrderCurrencyCode(String orderCurrencyCode) {
		this.orderCurrencyCode = orderCurrencyCode;
	}

	@Column(name = "original_increment_id", length = 50)
	public String getOriginalIncrementId() {
		return this.originalIncrementId;
	}

	public void setOriginalIncrementId(String originalIncrementId) {
		this.originalIncrementId = originalIncrementId;
	}

	@Column(name = "relation_child_id", length = 32)
	public String getRelationChildId() {
		return this.relationChildId;
	}

	public void setRelationChildId(String relationChildId) {
		this.relationChildId = relationChildId;
	}

	@Column(name = "relation_child_real_id", length = 32)
	public String getRelationChildRealId() {
		return this.relationChildRealId;
	}

	public void setRelationChildRealId(String relationChildRealId) {
		this.relationChildRealId = relationChildRealId;
	}

	@Column(name = "relation_parent_id", length = 32)
	public String getRelationParentId() {
		return this.relationParentId;
	}

	public void setRelationParentId(String relationParentId) {
		this.relationParentId = relationParentId;
	}

	@Column(name = "relation_parent_real_id", length = 32)
	public String getRelationParentRealId() {
		return this.relationParentRealId;
	}

	public void setRelationParentRealId(String relationParentRealId) {
		this.relationParentRealId = relationParentRealId;
	}

	@Column(name = "remote_ip")
	public String getRemoteIp() {
		return this.remoteIp;
	}

	public void setRemoteIp(String remoteIp) {
		this.remoteIp = remoteIp;
	}

	@Column(name = "shipping_method")
	public String getShippingMethod() {
		return this.shippingMethod;
	}

	public void setShippingMethod(String shippingMethod) {
		this.shippingMethod = shippingMethod;
	}

	@Column(name = "store_currency_code", length = 3)
	public String getStoreCurrencyCode() {
		return this.storeCurrencyCode;
	}

	public void setStoreCurrencyCode(String storeCurrencyCode) {
		this.storeCurrencyCode = storeCurrencyCode;
	}

	@Column(name = "store_name")
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "x_forwarded_for")
	public String getXForwardedFor() {
		return this.XForwardedFor;
	}

	public void setXForwardedFor(String XForwardedFor) {
		this.XForwardedFor = XForwardedFor;
	}

	@Column(name = "customer_note", length = 65535, columnDefinition = "TEXT")
	public String getCustomerNote() {
		return this.customerNote;
	}

	public void setCustomerNote(String customerNote) {
		this.customerNote = customerNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "total_item_count", nullable = false)
	public short getTotalItemCount() {
		return this.totalItemCount;
	}

	public void setTotalItemCount(short totalItemCount) {
		this.totalItemCount = totalItemCount;
	}

	@Column(name = "customer_gender")
	public Integer getCustomerGender() {
		return this.customerGender;
	}

	public void setCustomerGender(Integer customerGender) {
		this.customerGender = customerGender;
	}

	@Column(name = "hidden_tax_amount", precision = 12, scale = 4)
	public BigDecimal getHiddenTaxAmount() {
		return this.hiddenTaxAmount;
	}

	public void setHiddenTaxAmount(BigDecimal hiddenTaxAmount) {
		this.hiddenTaxAmount = hiddenTaxAmount;
	}

	@Column(name = "base_hidden_tax_amount", precision = 12, scale = 4)
	public BigDecimal getBaseHiddenTaxAmount() {
		return this.baseHiddenTaxAmount;
	}

	public void setBaseHiddenTaxAmount(BigDecimal baseHiddenTaxAmount) {
		this.baseHiddenTaxAmount = baseHiddenTaxAmount;
	}

	@Column(name = "shipping_hidden_tax_amount", precision = 12, scale = 4)
	public BigDecimal getShippingHiddenTaxAmount() {
		return this.shippingHiddenTaxAmount;
	}

	public void setShippingHiddenTaxAmount(BigDecimal shippingHiddenTaxAmount) {
		this.shippingHiddenTaxAmount = shippingHiddenTaxAmount;
	}

	@Column(name = "base_shipping_hidden_tax_amnt", precision = 12, scale = 4)
	public BigDecimal getBaseShippingHiddenTaxAmnt() {
		return this.baseShippingHiddenTaxAmnt;
	}

	public void setBaseShippingHiddenTaxAmnt(BigDecimal baseShippingHiddenTaxAmnt) {
		this.baseShippingHiddenTaxAmnt = baseShippingHiddenTaxAmnt;
	}

	@Column(name = "hidden_tax_invoiced", precision = 12, scale = 4)
	public BigDecimal getHiddenTaxInvoiced() {
		return this.hiddenTaxInvoiced;
	}

	public void setHiddenTaxInvoiced(BigDecimal hiddenTaxInvoiced) {
		this.hiddenTaxInvoiced = hiddenTaxInvoiced;
	}

	@Column(name = "base_hidden_tax_invoiced", precision = 12, scale = 4)
	public BigDecimal getBaseHiddenTaxInvoiced() {
		return this.baseHiddenTaxInvoiced;
	}

	public void setBaseHiddenTaxInvoiced(BigDecimal baseHiddenTaxInvoiced) {
		this.baseHiddenTaxInvoiced = baseHiddenTaxInvoiced;
	}

	@Column(name = "hidden_tax_refunded", precision = 12, scale = 4)
	public BigDecimal getHiddenTaxRefunded() {
		return this.hiddenTaxRefunded;
	}

	public void setHiddenTaxRefunded(BigDecimal hiddenTaxRefunded) {
		this.hiddenTaxRefunded = hiddenTaxRefunded;
	}

	@Column(name = "base_hidden_tax_refunded", precision = 12, scale = 4)
	public BigDecimal getBaseHiddenTaxRefunded() {
		return this.baseHiddenTaxRefunded;
	}

	public void setBaseHiddenTaxRefunded(BigDecimal baseHiddenTaxRefunded) {
		this.baseHiddenTaxRefunded = baseHiddenTaxRefunded;
	}

	@Column(name = "shipping_incl_tax", precision = 12, scale = 4)
	public BigDecimal getShippingInclTax() {
		return this.shippingInclTax;
	}

	public void setShippingInclTax(BigDecimal shippingInclTax) {
		this.shippingInclTax = shippingInclTax;
	}

	@Column(name = "base_shipping_incl_tax", precision = 12, scale = 4)
	public BigDecimal getBaseShippingInclTax() {
		return this.baseShippingInclTax;
	}

	public void setBaseShippingInclTax(BigDecimal baseShippingInclTax) {
		this.baseShippingInclTax = baseShippingInclTax;
	}

	@Column(name = "coupon_rule_name")
	public String getCouponRuleName() {
		return this.couponRuleName;
	}

	public void setCouponRuleName(String couponRuleName) {
		this.couponRuleName = couponRuleName;
	}

	@Column(name = "paypal_ipn_customer_notified")
	public Integer getPaypalIpnCustomerNotified() {
		return this.paypalIpnCustomerNotified;
	}

	public void setPaypalIpnCustomerNotified(Integer paypalIpnCustomerNotified) {
		this.paypalIpnCustomerNotified = paypalIpnCustomerNotified;
	}

	@Column(name = "gift_message_id")
	public Integer getGiftMessageId() {
		return this.giftMessageId;
	}

	public void setGiftMessageId(Integer giftMessageId) {
		this.giftMessageId = giftMessageId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesFlatOrderItem> getSalesFlatOrderItems() {
		return this.salesFlatOrderItems;
	}

	public void setSalesFlatOrderItems(Set<SalesFlatOrderItem> salesFlatOrderItems) {
		this.salesFlatOrderItems = salesFlatOrderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesPaymentTransaction> getSalesPaymentTransactions() {
		return this.salesPaymentTransactions;
	}

	public void setSalesPaymentTransactions(Set<SalesPaymentTransaction> salesPaymentTransactions) {
		this.salesPaymentTransactions = salesPaymentTransactions;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public SalesFlatOrderGrid getSalesFlatOrderGrid() {
		return this.salesFlatOrderGrid;
	}

	public void setSalesFlatOrderGrid(SalesFlatOrderGrid salesFlatOrderGrid) {
		this.salesFlatOrderGrid = salesFlatOrderGrid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesFlatOrderAddress> getSalesFlatOrderAddresses() {
		return this.salesFlatOrderAddresses;
	}

	public void setSalesFlatOrderAddresses(Set<SalesFlatOrderAddress> salesFlatOrderAddresses) {
		this.salesFlatOrderAddresses = salesFlatOrderAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesRecurringProfileOrder> getSalesRecurringProfileOrders() {
		return this.salesRecurringProfileOrders;
	}

	public void setSalesRecurringProfileOrders(Set<SalesRecurringProfileOrder> salesRecurringProfileOrders) {
		this.salesRecurringProfileOrders = salesRecurringProfileOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesFlatShipment> getSalesFlatShipments() {
		return this.salesFlatShipments;
	}

	public void setSalesFlatShipments(Set<SalesFlatShipment> salesFlatShipments) {
		this.salesFlatShipments = salesFlatShipments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<DownloadableLinkPurchased> getDownloadableLinkPurchaseds() {
		return this.downloadableLinkPurchaseds;
	}

	public void setDownloadableLinkPurchaseds(Set<DownloadableLinkPurchased> downloadableLinkPurchaseds) {
		this.downloadableLinkPurchaseds = downloadableLinkPurchaseds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesFlatOrderPayment> getSalesFlatOrderPayments() {
		return this.salesFlatOrderPayments;
	}

	public void setSalesFlatOrderPayments(Set<SalesFlatOrderPayment> salesFlatOrderPayments) {
		this.salesFlatOrderPayments = salesFlatOrderPayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesFlatInvoice> getSalesFlatInvoices() {
		return this.salesFlatInvoices;
	}

	public void setSalesFlatInvoices(Set<SalesFlatInvoice> salesFlatInvoices) {
		this.salesFlatInvoices = salesFlatInvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesFlatCreditmemo> getSalesFlatCreditmemos() {
		return this.salesFlatCreditmemos;
	}

	public void setSalesFlatCreditmemos(Set<SalesFlatCreditmemo> salesFlatCreditmemos) {
		this.salesFlatCreditmemos = salesFlatCreditmemos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrders")
	public Set<SalesBillingAgreement> getSalesBillingAgreements() {
		return this.salesBillingAgreements;
	}

	public void setSalesBillingAgreements(Set<SalesBillingAgreement> salesBillingAgreements) {
		this.salesBillingAgreements = salesBillingAgreements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesFlatOrder")
	public Set<SalesFlatOrderStatusHistory> getSalesFlatOrderStatusHistories() {
		return this.salesFlatOrderStatusHistories;
	}

	public void setSalesFlatOrderStatusHistories(Set<SalesFlatOrderStatusHistory> salesFlatOrderStatusHistories) {
		this.salesFlatOrderStatusHistories = salesFlatOrderStatusHistories;
	}

}
