package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SalesruleCoupon generated by hbm2java
 */
@Entity
@Table(name = "salesrule_coupon"
	, catalog = "magento"
	, uniqueConstraints = {@UniqueConstraint(columnNames = "code"), @UniqueConstraint(columnNames = {"rule_id", "is_primary"})})
public class SalesruleCoupon implements java.io.Serializable {

	private Integer couponId;
	private Salesrule salesrule;
	private String code;
	private Integer usageLimit;
	private Integer usagePerCustomer;
	private int timesUsed;
	private Date expirationDate;
	private Short isPrimary;
	private Date createdAt;
	private Short type;
	private Set<SalesruleCouponUsage> salesruleCouponUsages = new HashSet<SalesruleCouponUsage>(0);

	public SalesruleCoupon() {
	}

	public SalesruleCoupon(Salesrule salesrule, int timesUsed, Date createdAt) {
		this.salesrule = salesrule;
		this.timesUsed = timesUsed;
		this.createdAt = createdAt;
	}

	public SalesruleCoupon(Salesrule salesrule, String code, Integer usageLimit, Integer usagePerCustomer, int timesUsed, Date expirationDate, Short isPrimary, Date createdAt, Short type, Set<SalesruleCouponUsage> salesruleCouponUsages) {
		this.salesrule = salesrule;
		this.code = code;
		this.usageLimit = usageLimit;
		this.usagePerCustomer = usagePerCustomer;
		this.timesUsed = timesUsed;
		this.expirationDate = expirationDate;
		this.isPrimary = isPrimary;
		this.createdAt = createdAt;
		this.type = type;
		this.salesruleCouponUsages = salesruleCouponUsages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coupon_id", unique = true, nullable = false)
	public Integer getCouponId() {
		return this.couponId;
	}

	public void setCouponId(Integer couponId) {
		this.couponId = couponId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rule_id", nullable = false)
	public Salesrule getSalesrule() {
		return this.salesrule;
	}

	public void setSalesrule(Salesrule salesrule) {
		this.salesrule = salesrule;
	}

	@Column(name = "code", unique = true)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "usage_limit")
	public Integer getUsageLimit() {
		return this.usageLimit;
	}

	public void setUsageLimit(Integer usageLimit) {
		this.usageLimit = usageLimit;
	}

	@Column(name = "usage_per_customer")
	public Integer getUsagePerCustomer() {
		return this.usagePerCustomer;
	}

	public void setUsagePerCustomer(Integer usagePerCustomer) {
		this.usagePerCustomer = usagePerCustomer;
	}

	@Column(name = "times_used", nullable = false)
	public int getTimesUsed() {
		return this.timesUsed;
	}

	public void setTimesUsed(int timesUsed) {
		this.timesUsed = timesUsed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiration_date", length = 19)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "is_primary")
	public Short getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(Short isPrimary) {
		this.isPrimary = isPrimary;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "type")
	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesruleCoupon")
	public Set<SalesruleCouponUsage> getSalesruleCouponUsages() {
		return this.salesruleCouponUsages;
	}

	public void setSalesruleCouponUsages(Set<SalesruleCouponUsage> salesruleCouponUsages) {
		this.salesruleCouponUsages = salesruleCouponUsages;
	}

}
