package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.naver.mage4j.core.mage.core.model.resource.store.Store;

/**
 * TaxOrderAggregatedCreated generated by hbm2java
 */
@Entity
@Table(name = "tax_order_aggregated_created"
	, catalog = "magento"
	, uniqueConstraints = @UniqueConstraint(columnNames = {"period", "store_id", "code", "percent", "order_status"}))
public class TaxOrderAggregatedCreated implements java.io.Serializable {

	private Integer id;
	private Store coreStore;
	private Date period;
	private String code;
	private String orderStatus;
	private Float percent;
	private int ordersCount;
	private Float taxBaseAmountSum;

	public TaxOrderAggregatedCreated() {
	}

	public TaxOrderAggregatedCreated(String code, String orderStatus, int ordersCount) {
		this.code = code;
		this.orderStatus = orderStatus;
		this.ordersCount = ordersCount;
	}

	public TaxOrderAggregatedCreated(Store coreStore, Date period, String code, String orderStatus, Float percent, int ordersCount, Float taxBaseAmountSum) {
		this.coreStore = coreStore;
		this.period = period;
		this.code = code;
		this.orderStatus = orderStatus;
		this.percent = percent;
		this.ordersCount = ordersCount;
		this.taxBaseAmountSum = taxBaseAmountSum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getCoreStore() {
		return this.coreStore;
	}

	public void setCoreStore(Store coreStore) {
		this.coreStore = coreStore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "period", length = 10)
	public Date getPeriod() {
		return this.period;
	}

	public void setPeriod(Date period) {
		this.period = period;
	}

	@Column(name = "code", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "order_status", nullable = false, length = 50)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "percent", precision = 12, scale = 0)
	public Float getPercent() {
		return this.percent;
	}

	public void setPercent(Float percent) {
		this.percent = percent;
	}

	@Column(name = "orders_count", nullable = false)
	public int getOrdersCount() {
		return this.ordersCount;
	}

	public void setOrdersCount(int ordersCount) {
		this.ordersCount = ordersCount;
	}

	@Column(name = "tax_base_amount_sum", precision = 12, scale = 0)
	public Float getTaxBaseAmountSum() {
		return this.taxBaseAmountSum;
	}

	public void setTaxBaseAmountSum(Float taxBaseAmountSum) {
		this.taxBaseAmountSum = taxBaseAmountSum;
	}

}
