package com.naver.mage4j.core.mage.core.model.resource.model;

// Generated 2014. 7. 17 ���� 12:15:45 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * XmlconnectConfigData generated by hbm2java
 */
@Entity
@Table(name = "xmlconnect_config_data"
	, catalog = "magento"
	, uniqueConstraints = @UniqueConstraint(columnNames = {"application_id", "category", "path"}))
public class XmlconnectConfigData implements java.io.Serializable {

	private XmlconnectConfigDataId id;
	private XmlconnectApplication xmlconnectApplication;

	public XmlconnectConfigData() {
	}

	public XmlconnectConfigData(XmlconnectConfigDataId id, XmlconnectApplication xmlconnectApplication) {
		this.id = id;
		this.xmlconnectApplication = xmlconnectApplication;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "applicationId", column = @Column(name = "application_id", nullable = false)),
		@AttributeOverride(name = "category", column = @Column(name = "category", nullable = false, length = 60)),
		@AttributeOverride(name = "path", column = @Column(name = "path", nullable = false, length = 250)),
		@AttributeOverride(name = "value", column = @Column(name = "value", nullable = false, length = 65535, columnDefinition = "TEXT"))})
	public XmlconnectConfigDataId getId() {
		return this.id;
	}

	public void setId(XmlconnectConfigDataId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id", nullable = false, insertable = false, updatable = false)
	public XmlconnectApplication getXmlconnectApplication() {
		return this.xmlconnectApplication;
	}

	public void setXmlconnectApplication(XmlconnectApplication xmlconnectApplication) {
		this.xmlconnectApplication = xmlconnectApplication;
	}

}
